export default {
  page: 'about_company',
  title: 'Контент: О компании: Редактирование',
  groups: [
    {
      tabName: 'Элемент',
      name: 'element_tab',
      layoutForm: 'horizontal',
      fields: ['element_tab__title_block', 'element_tab__container_block'],
    },
    {
      tabName: 'Подробно',
      name: 'more_tab',
      fields: ['more_tab__title_block', 'more_tab__container_block'],
    },
    {
      tabName: 'SEO',
      name: 'seo_tab',
      layoutForm: 'horizontal',
      fields: ['seo_tab__container_block'],
    },
  ],
  fields: [
    {
      name: 'element_tab__title_block',
      type: 'div',
      style: {},
      cssClass: ['bg-white', 'p-6', 'border-b', 'border-borderColor'],
      fields: ['title_1'],
    },
    {
      name: 'more_tab__title_block',
      type: 'div',
      cssClass: ['bg-white', 'p-6', 'border-b', 'border-borderColor'],
      fields: ['title_2'],
    },
    {
      text: 'Элемент',
      name: 'title_1',
      type: 'label',
      cssClass: ['font-medium', 'text-base'],
    },
    {
      text: 'Детальная информация',
      name: 'title_2',
      type: 'label',
      cssClass: ['font-medium', 'text-base'],
    },
    {
      name: 'element_tab__container_block',
      type: 'div',
      style: {},
      cssClass: ['grid', 'bg-white', 'grid-cols-[400px_1fr]', 'p-6', 'gap-2'],
      fields: ['element_tab__body_block_left', 'element_tab__body_block_rigth'],
    },
    {
      name: 'element_tab__body_block_left',
      type: 'div',
      cssClass: ['flex', 'gap-4', 'items-end', 'flex-col'],
      fields: [
        'id_field_label',
        'create_field_label',
        'updated_field_label',
        'active_switch_label',
        'company_name_label',
        'slug_label',
        'sorting_label',
        'link_label',
      ],
    },
    {
      name: 'element_tab__body_block_rigth',
      type: 'div',
      cssClass: ['flex', 'gap-4', 'items-start', 'flex-col'],
      fields: [
        'id_text',
        'create_text',
        'updated_text',
        'active_switch',
        'company_name_input',
        'slug_input',
        'sorting_input',
        'link_input',
        'buttons_container_block',
      ],
    },
    {
      text: 'ID:',
      name: 'id_field_label',
      type: 'label',
      style: {},
    },
    {
      text: '456',
      name: 'id_text',
      type: 'label',
      style: {},
      parentClass: ['w-480', 'font-medium'],
    },
    {
      text: 'Создан:',
      name: 'create_field_label',
      type: 'label',
      style: {},
    },
    {
      text: '23.05.2022   17:11:11  Алексей',
      name: 'create_text',
      type: 'label',
      style: {},
      parentClass: ['w-480', 'font-medium'],
    },
    {
      text: 'Изменён:',
      name: 'updated_field_label',
      type: 'label',
      style: {},
    },
    {
      text: '24.05.2022   16:11:11  Алексей',
      name: 'updated_text',
      type: 'label',
      style: {},
      parentClass: ['w-480', 'font-medium'],
    },
    {
      text: 'Активность:',
      name: 'active_switch_label',
      type: 'label',
      style: {},
    },
    {
      text: 'Название:',
      name: 'company_name_label',
      type: 'label',
      style: {},
      parentClass: ['h-10', 'flex', 'items-center'],
    },
    {
      text: 'Символьный код:',
      name: 'slug_label',
      type: 'label',
      style: {},
      parentClass: ['h-10', 'flex', 'items-center'],
    },
    {
      text: 'Сортировка:',
      name: 'sorting_label',
      type: 'label',
      style: {},
      parentClass: ['h-10', 'flex', 'items-center'],
    },
    {
      text: 'Ссылка:',
      name: 'link_label',
      type: 'label',
      style: {},
      parentClass: ['h-10', 'flex', 'items-center'],
    },
    {
      title: '',
      label: '',
      required: false,
      name: 'active_switch',
      value: true,
      type: 'boolean',
      viewType: 'switch',
      style: {},
      parentClass: ['w-480'],
    },
    {
      title: '',
      description: '',
      required: false,
      name: 'company_name_input',
      format: 'text',
      value: 'О компании',
      type: 'input',
      parentClass: ['w-480'],
    },
    {
      title: '',
      description: '',
      required: false,
      name: 'slug_input',
      format: 'text',
      value: 'o-kompanii',
      type: 'input',
      parentClass: ['w-480'],
    },
    {
      title: '',
      description: '',
      required: false,
      name: 'sorting_input',
      format: 'text',
      value: '500',
      type: 'input',
      parentClass: ['w-480'],
    },
    {
      title: '',
      description: '',
      required: false,
      name: 'link_input',
      format: 'text',
      value: '/main/o-kompanii',
      type: 'input',
      parentClass: ['w-480'],
    },
    {
      name: 'buttons_container_block',
      type: 'div',
      style: {},
      cssClass: ['flex', 'gap-2.5'],
      fields: ['cancel_button', 'save_button'],
    },
    {
      type: 'button',
      value: 'Сохранить',
      name: 'save_button',
      size: 'large',
      buttonType: 'primary',
      disabled: false,
      cssClass: [],
      style: {},
      icon: {},
      handler: {},
    },
    {
      type: 'button',
      value: 'Отмена',
      name: 'cancel_button',
      size: 'large',
      buttonType: 'default',
      disabled: false,
      cssClass: [],
      style: {},
      icon: {},
      handler: {},
    },
    {
      name: 'more_tab__container_block',
      type: 'div',
      style: {},
      cssClass: ['bg-white'],
      fields: ['more_tab__body_block'],
    },
    {
      name: 'more_tab__body_block',
      type: 'div',
      cssClass: {},
      fields: ['more_tab__editor_block', 'more_tab__buttons_container_block'],
    },
    {
      name: 'more_tab__editor_block',
      type: 'div',
      cssClass: ['h-80', 'p-6'],
      fields: ['editor_field'],
    },
    {
      name: 'more_tab__buttons_container_block',
      type: 'div',
      cssClass: ['flex', 'justify-end', 'p-6', 'gap-2'],
      fields: ['more_tab__cancel_button', 'more_tab__save_button'],
    },
    {
      type: 'button',
      value: 'Сохранить',
      name: 'more_tab__save_button',
      size: 'large',
      buttonType: 'primary',
      disabled: false,
      cssClass: [],
      style: {},
      icon: {},
      handler: {},
    },
    {
      type: 'button',
      value: 'Отмена',
      name: 'more_tab__cancel_button',
      size: 'large',
      buttonType: 'default',
      disabled: false,
      cssClass: [],
      style: {},
      icon: {},
      handler: {},
    },
    {
      label: 'SEO Текст страницы',
      description: '',
      name: 'editor_field',
      value: '<h1>Заголовок</h1>',
      type: 'editor',
      cssClass: ['h-80'],
      style: {},
      positionStyle: {},
    },
    {
      name: 'seo_tab__container_block',
      type: 'div',
      cssClass: ['bg-white'],
      fields: ['seo_tab__body_block_1'],
    },
    {
      name: 'seo_tab__body_block_1',
      type: 'div',
      cssClass: [],
      fields: [
        'seo_tab__title_block_1',
        'meta_title_block',
        'meta_description_block',
        'section_block',
        'seo_tab__title_block_2',
        'alt_template_block',
        'title_template_block',
        'file_name_template_block',
        'seo_tab__title_block_3',
        'availability_block',
        'search_tags_block',
        'seo_tab__buttons_container_block',
      ],
    },
    {
      text: 'Настройки SEO информации',
      name: 'seo_tab__title_block_1',
      type: 'label',
      parentClass: ['pt-4', 'ml-85', 'mb-6', 'font-semibold'],
      style: {
        fontSize: '16px',
        lineHeight: '24px',
      },
      cssClass: [],
    },
    {
      text: 'Настройки для картинок анонса элементов',
      name: 'seo_tab__title_block_2',
      type: 'label',
      parentClass: ['pt-4', 'ml-85', 'mb-6', 'mt-10', 'font-semibold'],
      style: {
        fontSize: '16px',
        lineHeight: '24px',
      },
    },
    {
      text: 'Дополнительно',
      name: 'seo_tab__title_block_3',
      type: 'label',
      parentClass: ['pt-4', 'ml-85', 'mb-6', 'mt-10', 'font-semibold'],
      style: {
        fontSize: '16px',
        lineHeight: '24px',
      },
    },
    {
      name: 'meta_title_block',
      type: 'div',
      cssClass: ['grid', 'grid-cols-[350px_1fr]', 'gap-2'],
      fields: ['meta_title_lable', 'meta_title_inputs_fields'],
    },
    {
      name: 'meta_title_inputs_fields',
      type: 'div',
      cssClass: [],
      fields: [
        'meta_title_input',
        'meta_title_checkbox',
        'sublable_input_1',
        'sublable_input_2',
        'sublable_input_3',
      ],
    },
    {
      text: 'Шаблон META TITLE:',
      name: 'meta_title_lable',
      type: 'label',
      parentClass: ['flex', 'justify-end', 'mt-2.5'],
      cssClass: [],
    },
    {
      title: '',
      description: '',
      required: false,
      name: 'meta_title_input',
      format: 'text',
      value: 'Интернет-магазин Популярных (ТОР) Гаджетов - ИгроРай',
      type: 'input',
      parentClass: ['max-w-580', 'dots_after_input', 'relative'],
    },
    {
      title: '',
      label: 'Изменить для этого раздела и его подразделов.',
      required: false,
      name: 'meta_title_checkbox',
      value: true,
      type: 'boolean',
      viewType: 'checkbox',
      style: {},
      parentClass: ['mt-1'],
    },
    {
      text: 'Интернет-магазин Популярных (ТОР) Гаджетов - ИгроРай',
      name: 'sublable_input_1',
      type: 'label',
      parentClass: ['mb-2'],
      cssClass: ['ml-6', 'font-medium'],
    },
    {
      text: 'Количество символов: 52',
      name: 'sublable_input_2',
      type: 'label',
      parentClass: [],
      cssClass: ['ml-6', 'font-normal', 'text-13px'],
    },
    {
      text: 'Количество слов: 6',
      name: 'sublable_input_3',
      type: 'label',
      parentClass: [],
      cssClass: ['ml-6', 'font-normal', 'text-13px'],
    },
    {
      name: 'meta_description_block',
      type: 'div',
      cssClass: ['grid', 'grid-cols-[350px_1fr]', 'gap-2', 'mt-8'],
      fields: ['meta_description_lable', 'meta_description_inputs_fields'],
    },
    {
      name: 'meta_description_inputs_fields',
      type: 'div',
      cssClass: [],
      fields: [
        'meta_description_input',
        'meta_description_checkbox',
        'sublable_description_input_1',
        'sublable_description_input_2',
      ],
    },
    {
      text: 'Шаблон META DESCRIPTION:',
      name: 'meta_description_lable',
      type: 'label',
      parentClass: ['flex', 'justify-end', 'mt-2.5'],
      cssClass: [],
    },
    {
      title: '',
      description: '',
      required: false,
      name: 'meta_description_input',
      format: 'text',
      value: '',
      type: 'input',
      parentClass: ['max-w-580', 'dots_after_input', 'relative'],
    },
    {
      title: '',
      label: 'Изменить для этого раздела и его подразделов.',
      required: false,
      name: 'meta_description_checkbox',
      value: false,
      type: 'boolean',
      viewType: 'checkbox',
      style: {},
      parentClass: ['mt-1'],
    },
    {
      text: 'Количество символов: 0',
      name: 'sublable_description_input_1',
      type: 'label',
      parentClass: [],
      cssClass: ['ml-6', 'font-normal', 'text-13px'],
    },
    {
      text: 'Количество слов: 0',
      name: 'sublable_description_input_2',
      type: 'label',
      parentClass: [],
      cssClass: ['ml-6', 'font-normal', 'text-13px'],
    },
    {
      name: 'section_block',
      type: 'div',
      cssClass: ['grid', 'grid-cols-[350px_1fr]', 'gap-2', 'mt-8'],
      fields: ['section_lable', 'section_inputs_fields'],
    },
    {
      name: 'section_inputs_fields',
      type: 'div',
      cssClass: [],
      fields: [
        'section_input',
        'section_checkbox',
        'sublable_section_input_1',
        'sublable_section_input_2',
      ],
    },
    {
      text: 'Заголовок раздела:',
      name: 'section_lable',
      type: 'label',
      parentClass: ['flex', 'justify-end', 'mt-2.5'],
      cssClass: [],
    },
    {
      title: '',
      description: '',
      required: false,
      name: 'section_input',
      format: 'text',
      value: '',
      type: 'input',
      parentClass: ['max-w-580', 'dots_after_input', 'relative'],
    },
    {
      title: '',
      label: 'Изменить для этого раздела и его подразделов.',
      required: false,
      name: 'section_checkbox',
      value: false,
      type: 'boolean',
      viewType: 'checkbox',
      style: {},
      parentClass: ['mt-1'],
    },
    {
      text: 'Количество символов: 0',
      name: 'sublable_section_input_1',
      type: 'label',
      parentClass: [],
      cssClass: ['ml-6', 'font-normal', 'text-13px'],
    },
    {
      text: 'Количество слов: 0',
      name: 'sublable_section_input_2',
      type: 'label',
      parentClass: [],
      cssClass: ['ml-6', 'font-normal', 'text-13px'],
    },
    {
      name: 'alt_template_block',
      type: 'div',
      cssClass: ['grid', 'grid-cols-[350px_1fr]', 'gap-2', 'mt-8'],
      fields: ['alt_template_lable', 'alt_template_inputs_fields'],
    },
    {
      name: 'alt_template_inputs_fields',
      type: 'div',
      cssClass: [],
      fields: [
        'alt_template_input',
        'alt_template_checkbox',
        'sublable_alt_template_input_1',
        'sublable_alt_template_input_2',
      ],
    },
    {
      text: 'Шаблон ALT:',
      name: 'alt_template_lable',
      type: 'label',
      parentClass: ['flex', 'justify-end', 'mt-2.5'],
      cssClass: [],
    },
    {
      title: '',
      description: '',
      required: false,
      name: 'alt_template_input',
      format: 'text',
      value: '',
      type: 'input',
      parentClass: ['max-w-580', 'dots_after_input', 'relative'],
    },
    {
      title: '',
      label: 'Изменить для этого раздела и его подразделов.',
      required: false,
      name: 'alt_template_checkbox',
      value: false,
      type: 'boolean',
      viewType: 'checkbox',
      style: {},
      parentClass: ['mt-1'],
    },
    {
      text: 'Количество символов: 0',
      name: 'sublable_alt_template_input_1',
      type: 'label',
      parentClass: [],
      cssClass: ['ml-6', 'font-normal', 'text-13px'],
    },
    {
      text: 'Количество слов: 0',
      name: 'sublable_alt_template_input_2',
      type: 'label',
      parentClass: [],
      cssClass: ['ml-6', 'font-normal', 'text-13px'],
    },
    {
      name: 'title_template_block',
      type: 'div',
      cssClass: ['grid', 'grid-cols-[350px_1fr]', 'gap-2', 'mt-8'],
      fields: ['title_template_lable', 'title_template_inputs_fields'],
    },
    {
      name: 'title_template_inputs_fields',
      type: 'div',
      cssClass: [],
      fields: [
        'title_template_input',
        'title_template_checkbox',
        'sublable_title_template_input_1',
        'sublable_title_template_input_2',
      ],
    },
    {
      text: 'Шаблон TITLE:',
      name: 'title_template_lable',
      type: 'label',
      parentClass: ['flex', 'justify-end', 'mt-2.5'],
      cssClass: [],
    },
    {
      title: '',
      description: '',
      required: false,
      name: 'title_template_input',
      format: 'text',
      value: '',
      type: 'input',
      parentClass: ['max-w-580', 'dots_after_input', 'relative'],
    },
    {
      title: '',
      label: 'Изменить для этого раздела и его подразделов.',
      required: false,
      name: 'title_template_checkbox',
      value: false,
      type: 'boolean',
      viewType: 'checkbox',
      style: {},
      parentClass: ['mt-1'],
    },
    {
      text: 'Количество символов: 0',
      name: 'sublable_title_template_input_1',
      type: 'label',
      parentClass: [],
      cssClass: ['ml-6', 'font-normal', 'text-13px'],
    },
    {
      text: 'Количество слов: 0',
      name: 'sublable_title_template_input_2',
      type: 'label',
      parentClass: [],
      cssClass: ['ml-6', 'font-normal', 'text-13px'],
    },
    {
      name: 'file_name_template_block',
      type: 'div',
      cssClass: ['grid', 'grid-cols-[350px_1fr]', 'gap-2', 'mt-8'],
      fields: ['file_name_template_lable', 'file_name_template_inputs_fields'],
    },
    {
      name: 'file_name_template_inputs_fields',
      type: 'div',
      cssClass: [],
      fields: ['file_name_template_input'],
    },
    {
      text: 'Шаблон имени файла:',
      name: 'file_name_template_lable',
      type: 'label',
      parentClass: ['flex', 'justify-end', 'mt-2.5'],
      cssClass: [],
    },
    {
      title: '',
      description: '',
      required: false,
      name: 'file_name_template_input',
      format: 'text',
      value: '',
      type: 'input',
      parentClass: ['max-w-580', 'dots_after_input', 'relative'],
    },
    {
      name: 'availability_block',
      type: 'div',
      cssClass: ['grid', 'grid-cols-[350px_1fr]', 'gap-2', 'mt-8'],
      fields: ['availability_lable', 'availability_inputs_fields'],
    },
    {
      name: 'availability_inputs_fields',
      type: 'div',
      cssClass: [],
      fields: ['availability_radio_group'],
    },
    {
      text: 'Доступность:',
      name: 'availability_lable',
      type: 'label',
      parentClass: ['flex', 'justify-end'],
      cssClass: [],
    },
    {
      title: '',
      label: '',
      required: false,
      name: 'availability_radio_group',
      value: 'all',
      type: 'radio',
      options: [
        {
          label: 'Все',
          value: 'all',
        },
        {
          label: 'По ссылке',
          value: 'onLink',
        },
        {
          label: 'Нет',
          value: 'no',
        },
      ],
      parentClass: [],
    },
    {
      name: 'search_tags_block',
      type: 'div',
      cssClass: ['grid', 'grid-cols-[350px_1fr]', 'gap-2', 'mt-8'],
      fields: ['search_tags_labels_block', 'search_tags_inputs_fields'],
    },
    {
      name: 'search_tags_inputs_fields',
      type: 'div',
      cssClass: [],
      fields: ['search_tags_input'],
    },
    {
      name: 'search_tags_labels_block',
      type: 'div',
      cssClass: ['text-end'],
      fields: ['search_tags_lable', 'search_tags_sublable'],
    },
    {
      text: 'Поисковые теги:',
      name: 'search_tags_lable',
      type: 'label',
      parentClass: [],
      cssClass: [],
    },
    {
      text: 'введите слова или словосочетания, разделяя их запятыми',
      name: 'search_tags_sublable',
      type: 'label',
      parentClass: [],
      cssClass: ['text-xs'],
    },
    {
      title: '',
      description: '',
      required: false,
      name: 'search_tags_input',
      format: 'text',
      value: '',
      type: 'input',
      cssClass: [],
      parentClass: ['max-w-580', 'dots_after_input', 'relative'],
    },
    {
      name: 'seo_tab__buttons_container_block',
      type: 'div',
      cssClass: ['flex', 'gap-2', 'mt-8', 'pb-10', 'ml-85'],
      fields: ['seo_tab__cancel_button', 'seo_tab__save_button'],
    },
    {
      type: 'button',
      value: 'Сохранить',
      name: 'seo_tab__save_button',
      size: 'large',
      buttonType: 'primary',
      disabled: false,
      cssClass: [],
      style: {},
      icon: {},
      handler: {},
    },
    {
      type: 'button',
      value: 'Отмена',
      name: 'seo_tab__cancel_button',
      size: 'large',
      buttonType: 'default',
      disabled: false,
      cssClass: [],
      style: {},
      icon: {},
      handler: {},
    },
  ],
}
