export default {
  title: 'Блог',
  page: 'blog_page_edit',
  useTitle: {
    title: 'Обзор ТВ-адаптера Xiaomi: Редактирование',
    operations: [
      {
        text: 'Копировать',
        icon: 'fa-solid fa-copy',
      },
      {
        text: 'Предпросмотр экспорта',
      },
      {
        text: 'Добавить',
        type: 'primary',
        icon: 'fa-solid fa-plus',
      },
      {
        text: 'Удалить',
        type: 'danger',
        icon: 'fa-solid fa-trash',
      },
    ],
    breadcrumbs: [
      {
        title: 'Главная',
        path: '/',
      },
      {
        title: 'Блог',
        path: '/main/blog_page',
      },
      {
        title: 'Обзоры товаров',
      },
      {
        title: 'Обзор ТВ-адаптера Xiaomi',
        path: '/main/blog_page_edit',
      },
    ],
  },
  groups: [
    {
      tabName: 'Новость',
      name: 'blog_page_edit_news',
      fields: ['blog_page_edit_tab_news__body_block'],
    },
    {
      tabName: 'Подробно',
      name: 'blog_page_edit_detail',
      fields: ['blog_page_edit_detail__body_block'],
    },
  ],
  fields: [
    {
      name: 'blog_page_edit_tab_news__body_block',
      type: 'div',
      cssClass: ['bg-white'],
      fields: [
        'blog_page_edit_tab_news__title_block',
        'blog_page_edit_tab_news__content_block',
      ],
    },
    {
      name: 'blog_page_edit_detail__body_block',
      type: 'div',
      cssClass: ['bg-white'],
      fields: ['blog_page_edit_detail__content_block'],
    },
    {
      name: 'blog_page_edit_detail__content_block',
      type: 'div',
      cssClass: ['flex', 'flex-col', 'gap-6', 'w-[700px]', 'mx-auto', 'p-6'],
      fields: [
        'blog_page_edit_detail__title_announcement',
        'blog_page_edit_detail__content_announcement',
        'blog_page_edit_detail__title_detail_info',
        'blog_page_edit_detail__detail_info_content',
      ],
    },
    {
      text: 'Информация для анонса',
      name: 'blog_page_edit_detail__title_announcement',
      type: 'label',
      parentClass: [
        'ml-[155px]',
        'w-max',
        'relative',
        'before:absolute',
        'before:left-[-30px]',
        'before:top-1/2',
        'before:block',
        'before:w-5',
        'before:border-t',
        'before:border-dividerColor',
        'after:absolute',
        'after:right-[-100%]',
        'after:top-1/2',
        'after:block',
        'after:w-[90%]',
        'after:border-t',
        'after:border-dividerColor',
      ],
      cssClass: ['font-medium', 'text-base'],
    },
    {
      name: 'blog_page_edit_detail__content_announcement',
      type: 'div',
      fields: [
        'blog_page_edit_detail__announcement_image_file_input',
        'blog_page_edit_detail__announcement_description_area_text',
      ],
    },
    {
      name: 'blog_page_edit_detail__detail_info_content',
      type: 'div',
      fields: [
        'blog_page_edit_detail__detail_info_image_file_input',
        'blog_page_edit_detail__detail_info_description_radio_group',
        'blog_page_edit_detail__detail_info_editor_field',
        'blog_page_edit_detail__detail_info_buttons_block',
      ],
    },
    {
      title: 'Изображение',
      titlePosition: 'left',
      titleClass: ['mt-2'],
      name: 'blog_page_edit_detail__announcement_image_file_input',
      value: '',
      type: 'file',
      maxCount: 3,
      fileType: 'image',
      parentClass: ['w-500', 'mb-4'],
    },
    {
      title: 'Изображение',
      titlePosition: 'left',
      titleClass: ['mt-2'],
      name: 'blog_page_edit_detail__detail_info_image_file_input',
      value: '',
      type: 'file',
      maxCount: 3,
      fileType: 'image',
      parentClass: ['w-500'],
    },
    {
      title: 'Описание',
      titlePosition: 'left',
      titleClass: ['mt-2'],
      name: 'blog_page_edit_detail__announcement_description_area_text',
      value: '',
      type: 'textarea',
      parentClass: ['w-500'],
      minRows: 3,
    },
    {
      text: 'Подробная информация',
      name: 'blog_page_edit_detail__title_detail_info',
      type: 'label',
      parentClass: [
        'mt-10',
        'ml-[155px]',
        'w-max',
        'relative',
        'before:absolute',
        'before:left-[-30px]',
        'before:top-1/2',
        'before:block',
        'before:w-5',
        'before:border-t',
        'before:border-dividerColor',
        'after:absolute',
        'after:right-[-100%]',
        'after:top-1/2',
        'after:block',
        'after:w-[90%]',
        'after:border-t',
        'after:border-dividerColor',
      ],
      cssClass: ['font-medium', 'text-base'],
    },
    {
      name: 'blog_page_edit_detail__detail_info_description_radio_group',
      value: 'text',
      type: 'radio',
      parentClass: ['w-500', 'ml-[157px]', 'mt-6'],
      options: [
        {
          label: 'Текст',
          value: 'text',
        },
        {
          label: 'HTML',
          value: 'html',
        },
        {
          label: 'Визуальный редактор',
          value: 'visual-edit',
        },
      ],
    },
    {
      title: 'Описание',
      titlePosition: 'left',
      titleClass: ['mt-2'],
      name: 'blog_page_edit_detail__detail_info_editor_field',
      value: '',
      type: 'editor',
      cssClass: ['h-80'],
      parentClass: ['w-500'],
    },
    {
      name: 'blog_page_edit_tab_news__title_block',
      type: 'div',
      cssClass: ['w-full', 'p-6', 'border-b', 'border-borderColor'],
      fields: ['blog_page_edit_tab_news__title'],
    },
    {
      text: 'Статья',
      name: 'blog_page_edit_tab_news__title',
      type: 'label',
      cssClass: ['font-medium', 'text-base'],
    },
    {
      name: 'blog_page_edit_tab_news__content_block',
      type: 'div',
      cssClass: ['flex', 'flex-col', 'gap-6', 'w-[700px]', 'mx-auto', 'p-6'],
      fields: [
        'blog_page_edit_tab_news__active_switch',
        'blog_page_edit_tab_news__input_title',
        'blog_page_edit_tab_news__slug',
        'blog_page_edit_tab_news__sorting',
        'blog_page_edit_tab_news__buttons_block',
      ],
    },
    {
      title: 'Активность',
      titlePosition: 'left',
      name: 'blog_page_edit_tab_news__active_switch',
      value: true,
      type: 'boolean',
      viewType: 'switch',
      parentClass: ['w-500'],
    },
    {
      title: 'Заголовок',
      titleClass: ['mt-2'],
      titlePosition: 'left',
      name: 'blog_page_edit_tab_news__input_title',
      format: 'text',
      value: 'Обзор ТВ-адаптера Xiaomi',
      type: 'input',
      size: 'large',
      parentClass: ['w-500'],
      validation: {
        type: 'string',
        rules: [
          {
            type: 'min',
            params: [5],
          },
          {
            type: 'max',
            params: [50],
          },
        ],
      },
    },
    {
      title: 'Символьный код',
      titleClass: ['mt-2'],
      titlePosition: 'left',
      name: 'blog_page_edit_tab_news__slug',
      format: 'text',
      value: '',
      type: 'input',
      size: 'large',
      parentClass: ['w-500'],
    },
    {
      title: 'Сортировка',
      titleClass: ['mt-2'],
      titlePosition: 'left',
      name: 'blog_page_edit_tab_news__sorting',
      format: 'text',
      value: '',
      type: 'input',
      size: 'large',
      parentClass: ['w-500'],
    },
    {
      name: 'blog_page_edit_tab_news__buttons_block',
      type: 'div',
      cssClass: ['flex', 'gap-2.5', 'ml-[155px]'],
      fields: [
        'blog_page_edit_tab_news__cancel_button',
        'blog_page_edit_tab_news__save_button',
      ],
    },
    {
      type: 'button',
      value: 'Сохранить',
      name: 'blog_page_edit_tab_news__save_button',
      size: 'large',
      buttonType: 'primary',
      disabled: false,
      handlers: [
        {
          name: 'pushData',
          params: {
            pageName: 'blog_page_edit',
            blockName: 'blog_page_edit_tab_news__content_block',
            endpoint: 'https://ekat.sergeivl.ru/api/tests/request',
          },
        },
        {
          name: 'resetBlockData',
          params: {
            pageName: 'about_company',
            blockName: 'blog_page_edit_tab_news__content_block',
          },
        },
      ],
    },
    {
      type: 'button',
      value: 'Отмена',
      name: 'blog_page_edit_tab_news__cancel_button',
      size: 'large',
      buttonType: 'default',
      disabled: false,
    },
    {
      name: 'blog_page_edit_detail__detail_info_buttons_block',
      type: 'div',
      cssClass: ['flex', 'gap-2.5', 'ml-[155px]', 'mt-4'],
      fields: [
        'blog_page_edit_detail__detail_info_cancel_button',
        'blog_page_edit_detail__detail_info_save_button',
      ],
    },
    {
      type: 'button',
      value: 'Сохранить',
      name: 'blog_page_edit_detail__detail_info_save_button',
      size: 'large',
      buttonType: 'primary',
      disabled: false,
      handlers: [
        {
          name: 'pushData',
          params: {
            pageName: 'blog_page_edit',
            blockName: 'blog_page_edit_detail__content_block',
            endpoint: 'https://ekat.sergeivl.ru/api/tests/request',
          },
        },
        {
          name: 'resetBlockData',
          params: {
            pageName: 'about_company',
            blockName: 'blog_page_edit_detail__content_block',
          },
        },
      ],
    },
    {
      type: 'button',
      value: 'Отмена',
      name: 'blog_page_edit_detail__detail_info_cancel_button',
      size: 'large',
      buttonType: 'default',
      disabled: false,
    },
  ],
}
