export default {
  page: 'catalog_edit',

  useTitle: {
    title: 'Каталог товаров: Раздел каталога: Редактирование',
    breadcrumbs: [
      {
        title: 'Главная',
        path: '/',
      },
      {
        title: 'Каталог',
      },
      {
        title: 'Каталог товаров',
        path: '/main/catalog_edit',
      },
    ],
  },
  groups: [
    {
      tabName: 'Раздел каталога',
      name: 'catalog_part_tab',
      fields: ['catalog_part__title_block', 'catalog_part__container_block'],
    },
    {
      tabName: 'SEO',
      name: 'seo_tab',
      fields: ['seo_tab__title_block', 'seo_tab__container_block'],
    },
    {
      tabName: 'Офферы',
      name: 'Offers',
      fields: ['offers__title_block', 'offers__container_block'],
    },
  ],
  fields: [
    {
      name: 'catalog_part__title_block',
      type: 'div',
      cssClass: ['bg-white', 'p-6', 'border-b', 'border-borderColor'],
      fields: ['title_1'],
    },
    {
      name: 'seo_tab__title_block',
      type: 'div',
      cssClass: ['bg-white', 'p-6', 'border-b', 'border-borderColor'],
      fields: ['title_2'],
    },
    {
      name: 'offers__title_block',
      type: 'div',
      cssClass: ['bg-white', 'p-6', 'border-b', 'border-borderColor'],
      fields: ['title_4'],
    },
    {
      text: 'Добавить раздел',
      name: 'title_1',
      type: 'label',
      cssClass: ['font-medium', 'text-base'],
    },
    {
      text: 'Настройки SEO информации',
      name: 'title_2',
      type: 'label',
      cssClass: ['font-medium', 'text-base'],
    },
    {
      text: 'Офферы магазина',
      name: 'title_4',
      type: 'label',
      cssClass: ['font-medium', 'text-base'],
    },
    {
      name: 'catalog_part__container_block',
      type: 'div',
      cssClass: ['bg-white', 'p-6'],
      fields: ['catalog_part__body_block'],
    },
    {
      name: 'catalog_part__body_block',
      type: 'div',
      cssClass: ['flex', 'gap-6', 'flex-col', 'w-[800px]', 'ml-[8vw]'],
      fields: [
        'section_settings_block',
        'create_text',
        'updated_text',
        'active_switch',
        'parent_part_input',
        'title_name_input',
        'catalog_part__slug_input',
        'image_file_input',
        'icon_section_input',
        'banner_settings_block',
        'link_input',
        'photo_block',
        'visible_menu_group',
        'description_area_text',
        'buttons_container_block',
      ],
    },
    {
      cssClass: ['flex', 'flex-col', 'items-center'],
      fields: ['section_settings_title'],
      name: 'section_settings_block',
      type: 'div',
    },
    {
      cssClass: ['font-medium', 'text-base'],
      name: 'section_settings_title',
      parentClass: [
        'w-max',
        'mt-6',
        'relative',
        'before:absolute',
        'before:left-[-30px]',
        'before:top-1/2',
        'before:block',
        'before:w-5',
        'before:border-t',
        'before:border-dividerColor',
        'after:absolute',
        'after:right-[-100%]',
        'after:top-1/2',
        'after:block',
        'after:w-[90%]',
        'after:border-t',
        'after:border-dividerColor',
      ],
      text: 'Настройка раздела',
      type: 'label',
    },
    {
      title: 'Создан',
      titlePosition: 'left',
      titleClass: ['flex', 'items-center'],
      text: '23.05.2022   17:11:11  Алексей',
      name: 'create_text',
      type: 'label',
      parentClass: ['w-500', 'font-medium'],
    },
    {
      title: 'Изменён',
      titlePosition: 'left',
      titleClass: ['flex', 'items-center'],
      text: '24.05.2022   16:11:11  Алексей',
      name: 'updated_text',
      type: 'label',
      parentClass: ['w-500', 'font-medium'],
    },
    {
      title: 'Раздел активен',
      titlePosition: 'left',
      titleClass: ['flex', 'items-center'],
      name: 'active_switch',
      value: true,
      type: 'boolean',
      viewType: 'switch',
      parentClass: ['w-500'],
    },
    {
      title: 'Родительский раздел',
      titlePosition: 'left',
      titleClass: ['h-10', 'flex', 'items-center'],
      name: 'parent_part_input',
      format: 'text',
      value: 'Верхний уровень',
      type: 'input',
      parentClass: ['w-500'],
      validationType: 'string',
      validations: [
        {
          type: 'required',
          params: ['Это поле обязательно для заполнения'],
        },
      ],
    },
    {
      title: 'Название',
      titlePosition: 'left',
      titleClass: ['h-10', 'flex', 'items-center'],
      name: 'title_name_input',
      format: 'text',
      value: 'Sony Playstation 5',
      type: 'input',
      parentClass: ['w-500'],
    },
    {
      title: 'Символьный код',
      titlePosition: 'left',
      titleClass: ['h-10', 'flex', 'items-center'],
      name: 'catalog_part__slug_input',
      format: 'text',
      value: 'sony-playstation-5',
      type: 'input',
      parentClass: ['w-500'],
    },
    {
      title: 'Изображение',
      titlePosition: 'left',
      titleClass: ['mt-2'],
      name: 'image_file_input',
      value: '',
      type: 'file',
      maxCount: 3,
      fileType: 'image',
      parentClass: ['w-500'],
    },
    {
      title: 'Иконка раздела',
      titlePosition: 'left',
      titleClass: ['mt-2'],
      name: 'icon_section_input',
      value: '',
      type: 'file',
      maxCount: 3,
      fileType: 'image',
      parentClass: ['w-500'],
    },
    {
      cssClass: ['flex', 'flex-col', 'items-center'],
      fields: ['banner_settings_title'],
      name: 'banner_settings_block',
      type: 'div',
    },
    {
      cssClass: ['font-medium', 'text-base'],
      name: 'banner_settings_title',
      parentClass: [
        'w-max',
        'mt-6',
        'relative',
        'before:absolute',
        'before:left-[-30px]',
        'before:top-1/2',
        'before:block',
        'before:w-5',
        'before:border-t',
        'before:border-dividerColor',
        'after:absolute',
        'after:right-[-200%]',
        'after:top-1/2',
        'after:block',
        'after:w-[180%]',
        'after:border-t',
        'after:border-dividerColor',
      ],
      text: 'Баннер',
      type: 'label',
    },
    {
      format: 'text',
      name: 'link_input',
      parentClass: ['w-500'],
      title: 'Ссылка',
      titleClass: ['h-10', 'flex', 'items-center'],
      titlePosition: 'left',
      type: 'input',
      value: '',
    },
    {
      cssClass: ['flex', 'justify-center'],
      fields: ['image_pc_input', 'image_mobile_input'],
      name: 'photo_block',
      type: 'div',
    },
    {
      fileType: 'image',
      maxCount: 3,
      name: 'image_pc_input',
      title: 'Фото для ПК',
      titlePosition: 'top',
      type: 'file',
      value: '',
    },
    {
      fileType: 'image',
      maxCount: 3,
      name: 'image_mobile_input',
      title: 'Фото для мобильного',
      titlePosition: 'top',
      type: 'file',
      value: '',
    },
    {
      name: 'visible_menu_group',
      options: [
        {
          label: 'Бургер меню',
          value: 'burger-menu',
        },
        {
          label: 'Основное меню',
          value: 'main-menu',
        },
        {
          label: 'Список категорий',
          value: 'category-list',
        },
      ],
      parentClass: ['w-500'],
      title: 'Отображать в меню',
      titleClass: ['flex', 'items-center'],
      titlePosition: 'left',
      type: 'boolean',
      value: [],
      viewType: 'groupСheckbox',
    },
    {
      cssClass: ['h-[300px]'],
      minRows: 10,
      name: 'description_area_text',
      parentClass: ['w-500'],
      title: 'Описание',
      titleClass: ['h-10', 'flex', 'items-center'],
      titlePosition: 'left',
      type: 'editor',
      value: '',
    },
    {
      name: 'buttons_container_block',
      type: 'div',
      cssClass: ['flex', 'gap-2.5'],
      fields: ['cancel_button', 'save_button'],
      parentClass: ['w-500', 'flex', 'justify-end', 'ml-2'],
    },
    {
      type: 'button',
      value: 'Сохранить',
      name: 'save_button',
      size: 'large',
      buttonType: 'primary',
      disabled: false,
      handlers: [
        {
          name: 'pushData',
          params: {
            pageName: 'catalog_edit',
            blockName: 'catalog_part__body_block',
            endpoint: 'https://ekat.sergeivl.ru/api/tests/request',
          },
        },
        {
          name: 'resetBlockData',
          params: {
            pageName: 'catalog_edit',
            blockName: 'catalog_part__body_block',
          },
        },
      ],
    },
    {
      type: 'button',
      value: 'Отмена',
      name: 'cancel_button',
      size: 'large',
      buttonType: 'default',
      disabled: false,
    },
    {
      name: 'seo_tab__container_block',
      type: 'div',
      cssClass: ['bg-white'],
      fields: ['seo_tab__body_block_1'],
    },
    {
      name: 'seo_tab__body_block_1',
      type: 'div',
      fields: [
        'product_settings_block',
        'meta_title_block',
        'meta_description_block',
        'section_block',
        'availability_block',
        'search_tags_block',
        'settings_preview_block',
        'preview_atl_block',
        'preview_title_block',
        'preview_filename_block',
        'settings_images_product_block',
        'images_product_atl_block',
        'images_product_title_block',
        'images_product_filename_block',
        'settings_images_chapter_block',
        'images_chapter_atl_block',
        'images_chapter_title_block',
        'images_chapter_filename_block',
        'additional_fields_block',
        'additional_fields_containter_block',
        'additional_fields_meta_title_block',
        'additional_fields_meta_desc_block',
        'additional_fields_parent_coollection_block',
        'additional_fields_product_collection_block',
        'property_block',
        'property_columns_block',
        'additional_fields_hidden_filters_block',
        'seo_tab__buttons_container_block',
      ],
    },
    {
      cssClass: ['flex', 'flex-col', 'items-center'],
      fields: ['product_settings_title'],
      name: 'product_settings_block',
      type: 'div',
    },
    {
      cssClass: ['font-medium', 'text-base'],
      name: 'product_settings_title',
      parentClass: [
        'w-max',
        'mt-6',
        'relative',
        'before:absolute',
        'before:left-[-30px]',
        'before:top-1/2',
        'before:block',
        'before:w-5',
        'before:border-t',
        'before:border-dividerColor',
        'after:absolute',
        'after:right-[-75%]',
        'after:top-1/2',
        'after:block',
        'after:w-[75%]',
        'after:border-t',
        'after:border-dividerColor',
      ],
      text: 'Настройки для товаров',
      type: 'label',
    },
    {
      name: 'meta_title_block',
      type: 'div',
      cssClass: ['grid', 'grid-cols-[350px_1fr]', 'gap-2', 'pt-6'],
      fields: ['meta_title_lable', 'meta_title_inputs_fields'],
    },
    {
      name: 'meta_title_inputs_fields',
      type: 'div',
      fields: [
        'meta_title_input',
        'meta_title_checkbox',
        'sublable_input_1',
        'sublable_input_2',
        'sublable_input_3',
      ],
    },
    {
      text: 'Шаблон META TITLE:',
      name: 'meta_title_lable',
      type: 'label',
      parentClass: ['flex', 'justify-end', 'mt-2.5'],
    },
    {
      name: 'meta_title_input',
      format: 'text',
      value: 'Интернет-магазин Популярных (ТОР) Гаджетов - ИгроРай',
      type: 'input',
      parentClass: ['max-w-580', 'dots_after_input', 'relative'],
      validationType: 'string',
      validations: [
        {
          type: 'required',
          params: ['Это поле обязательно для заполнения'],
        },
      ],
    },
    {
      label: 'Изменить для этого раздела и его подразделов.',
      name: 'meta_title_checkbox',
      value: true,
      type: 'boolean',
      viewType: 'checkbox',
      parentClass: ['mt-1'],
    },
    {
      text: 'Интернет-магазин Популярных (ТОР) Гаджетов - ИгроРай',
      name: 'sublable_input_1',
      type: 'label',
      parentClass: ['mb-2'],
      cssClass: ['ml-6', 'font-medium'],
    },
    {
      text: 'Количество символов: 52',
      name: 'sublable_input_2',
      type: 'label',
      cssClass: ['ml-6', 'font-normal', 'text-13px'],
    },
    {
      text: 'Количество слов: 6',
      name: 'sublable_input_3',
      type: 'label',
      cssClass: ['ml-6', 'font-normal', 'text-13px'],
    },
    {
      name: 'meta_description_block',
      type: 'div',
      cssClass: ['grid', 'grid-cols-[350px_1fr]', 'gap-2', 'mt-8'],
      fields: ['meta_description_lable', 'meta_description_inputs_fields'],
    },
    {
      name: 'meta_description_inputs_fields',
      type: 'div',
      fields: [
        'meta_description_input',
        'meta_description_checkbox',
        'sublable_description_input_1',
        'sublable_description_input_2',
      ],
    },
    {
      text: 'Шаблон META DESCRIPTION:',
      name: 'meta_description_lable',
      type: 'label',
      parentClass: ['flex', 'justify-end', 'mt-2.5'],
    },
    {
      name: 'meta_description_input',
      format: 'text',
      value: '',
      type: 'input',
      parentClass: ['max-w-580', 'dots_after_input', 'relative'],
    },
    {
      label: 'Изменить для этого раздела и его подразделов.',
      name: 'meta_description_checkbox',
      value: false,
      type: 'boolean',
      viewType: 'checkbox',
      parentClass: ['mt-1'],
    },
    {
      text: 'Количество символов: 0',
      name: 'sublable_description_input_1',
      type: 'label',
      cssClass: ['ml-6', 'font-normal', 'text-13px'],
    },
    {
      text: 'Количество слов: 0',
      name: 'sublable_description_input_2',
      type: 'label',
      cssClass: ['ml-6', 'font-normal', 'text-13px'],
    },
    {
      name: 'section_block',
      type: 'div',
      cssClass: ['grid', 'grid-cols-[350px_1fr]', 'gap-2', 'mt-8'],
      fields: ['section_lable', 'section_inputs_fields'],
    },
    {
      name: 'section_inputs_fields',
      type: 'div',
      fields: [
        'section_input',
        'section_checkbox',
        'sublable_section_input_1',
        'sublable_section_input_2',
      ],
    },
    {
      text: 'Заголовок раздела:',
      name: 'section_lable',
      type: 'label',
      parentClass: ['flex', 'justify-end', 'mt-2.5'],
    },
    {
      name: 'section_input',
      format: 'text',
      value: '',
      type: 'input',
      parentClass: ['max-w-580', 'dots_after_input', 'relative'],
    },
    {
      label: 'Изменить для этого раздела и его подразделов.',
      name: 'section_checkbox',
      value: false,
      type: 'boolean',
      viewType: 'checkbox',
      parentClass: ['mt-1'],
    },
    {
      text: 'Количество символов: 0',
      name: 'sublable_section_input_1',
      type: 'label',
      cssClass: ['ml-6', 'font-normal', 'text-13px'],
    },
    {
      text: 'Количество слов: 0',
      name: 'sublable_section_input_2',
      type: 'label',
      cssClass: ['ml-6', 'font-normal', 'text-13px'],
    },
    {
      name: 'availability_block',
      type: 'div',
      cssClass: ['grid', 'grid-cols-[350px_1fr]', 'gap-2', 'mt-8'],
      fields: ['availability_lable', 'availability_inputs_fields'],
    },
    {
      name: 'availability_inputs_fields',
      type: 'div',
      fields: ['availability_radio_group'],
    },
    {
      text: 'Доступность:',
      name: 'availability_lable',
      type: 'label',
      parentClass: ['flex', 'justify-end'],
    },
    {
      name: 'availability_radio_group',
      value: 'all',
      type: 'radio',
      options: [
        {
          label: 'Все',
          value: 'all',
        },
        {
          label: 'По ссылке',
          value: 'onLink',
        },
        {
          label: 'Нет',
          value: 'no',
        },
      ],
    },
    {
      name: 'search_tags_block',
      type: 'div',
      cssClass: ['grid', 'grid-cols-[350px_1fr]', 'gap-2', 'mt-8'],
      fields: ['search_tags_labels_block', 'search_tags_inputs_fields'],
    },
    {
      cssClass: ['flex', 'flex-col', 'items-center'],
      fields: ['settings_preview_title'],
      name: 'settings_preview_block',
      type: 'div',
    },
    {
      cssClass: ['font-medium', 'text-base'],
      name: 'settings_preview_title',
      parentClass: [
        'w-max',
        'mt-6',
        'relative',
        'before:absolute',
        'before:left-[-30px]',
        'before:top-1/2',
        'before:block',
        'before:w-5',
        'before:border-t',
        'before:border-dividerColor',
        'after:absolute',
        'after:right-[-75%]',
        'after:top-1/2',
        'after:block',
        'after:w-[75%]',
        'after:border-t',
        'after:border-dividerColor',
      ],
      text: 'Настройки картинок превью списка',
      type: 'label',
    },
    {
      cssClass: ['grid', 'grid-cols-[350px_1fr]', 'gap-2', 'pt-6'],
      fields: ['preview_atl_lable', 'preview_atl_inputs_fields'],
      name: 'preview_atl_block',
      type: 'div',
    },
    {
      fields: [
        'preview_atl_input',
        'preview_atl_checkbox',
        'preview_atl_sublable_input_1',
        'preview_atl_sublable_input_2',
      ],
      name: 'preview_atl_inputs_fields',
      type: 'div',
    },
    {
      name: 'preview_atl_lable',
      parentClass: ['flex', 'justify-end', 'mt-2.5'],
      text: 'Шаблон ATL:',
      type: 'label',
    },
    {
      format: 'text',
      name: 'preview_atl_input',
      parentClass: ['max-w-580', 'dots_after_input', 'relative'],
      type: 'input',
      validations: [
        {
          params: ['Это поле обязательно для заполнения'],
          type: 'required',
        },
      ],
      validationType: 'string',
      value: '',
    },
    {
      label: 'Изменить для этого раздела и его подразделов.',
      name: 'preview_atl_checkbox',
      parentClass: ['mt-1'],
      type: 'boolean',
      value: true,
      viewType: 'checkbox',
    },
    {
      cssClass: ['ml-6', 'font-normal', 'text-13px'],
      name: 'preview_atl_sublable_input_1',
      text: 'Количество символов: 52',
      type: 'label',
    },
    {
      cssClass: ['ml-6', 'font-normal', 'text-13px'],
      name: 'preview_atl_sublable_input_2',
      text: 'Количество слов: 6',
      type: 'label',
    },
    {
      cssClass: ['grid', 'grid-cols-[350px_1fr]', 'gap-2', 'pt-6'],
      fields: ['preview_title_lable', 'preview_title_inputs_fields'],
      name: 'preview_title_block',
      type: 'div',
    },
    {
      fields: [
        'preview_title_input',
        'preview_title_checkbox',
        'preview_title_sublable_input_1',
        'preview_title_sublable_input_2',
      ],
      name: 'preview_title_inputs_fields',
      type: 'div',
    },
    {
      name: 'preview_title_lable',
      parentClass: ['flex', 'justify-end', 'mt-2.5'],
      text: 'Шаблон TITLE:',
      type: 'label',
    },
    {
      format: 'text',
      name: 'preview_title_input',
      parentClass: ['max-w-580', 'dots_after_input', 'relative'],
      type: 'input',
      validations: [
        {
          params: ['Это поле обязательно для заполнения'],
          type: 'required',
        },
      ],
      validationType: 'string',
      value: '',
    },
    {
      label: 'Изменить для этого раздела и его подразделов.',
      name: 'preview_title_checkbox',
      parentClass: ['mt-1'],
      type: 'boolean',
      value: true,
      viewType: 'checkbox',
    },
    {
      cssClass: ['ml-6', 'font-normal', 'text-13px'],
      name: 'preview_title_sublable_input_1',
      text: 'Количество символов: 52',
      type: 'label',
    },
    {
      cssClass: ['ml-6', 'font-normal', 'text-13px'],
      name: 'preview_title_sublable_input_2',
      text: 'Количество слов: 6',
      type: 'label',
    },
    {
      cssClass: ['grid', 'grid-cols-[350px_1fr]', 'gap-2', 'pt-6'],
      fields: ['preview_filename_lable', 'preview_filename_inputs_fields'],
      name: 'preview_filename_block',
      type: 'div',
    },
    {
      fields: [
        'preview_filename_input',
        'preview_filename_checkbox_1',
        'preview_filename_checkbox_2',
        'preview_filename_checkbox_3',
        'preview_filename_space_info_block',
        'preview_filename_sublable_input_1',
        'preview_filename_sublable_input_2',
      ],
      name: 'preview_filename_inputs_fields',
      type: 'div',
    },
    {
      name: 'preview_filename_lable',
      parentClass: ['flex', 'justify-end', 'mt-2.5'],
      text: 'Шаблон имени файла:',
      type: 'label',
    },
    {
      format: 'text',
      name: 'preview_filename_input',
      parentClass: ['max-w-580', 'dots_after_input', 'relative'],
      type: 'input',
      validations: [
        {
          params: ['Это поле обязательно для заполнения'],
          type: 'required',
        },
      ],
      validationType: 'string',
      value: '',
    },
    {
      label: 'Изменить для этого раздела и его подразделов.',
      name: 'preview_filename_checkbox_1',
      parentClass: ['mt-1'],
      type: 'boolean',
      value: true,
      viewType: 'checkbox',
    },
    {
      label: 'Привести к нижнему регистру.',
      name: 'preview_filename_checkbox_2',
      parentClass: ['mt-1'],
      type: 'boolean',
      value: true,
      viewType: 'checkbox',
    },
    {
      label: 'Транслировать.',
      name: 'preview_filename_checkbox_3',
      parentClass: ['mt-1'],
      type: 'boolean',
      value: true,
      viewType: 'checkbox',
    },
    {
      cssClass: ['flex', 'items-center'],
      fields: [
        'preview_filename_space_info_input',
        'preview_filename_space_info_label',
      ],
      name: 'preview_filename_space_info_block',
      type: 'div',
    },
    {
      format: 'text',
      name: 'preview_filename_space_info_input',
      parentClass: ['max-w-[73px]'],
      type: 'input',
      validations: [
        {
          params: ['Это поле обязательно для заполнения'],
          type: 'required',
        },
      ],
      validationType: 'string',
      value: '-',
    },
    {
      cssClass: ['ml-6', 'font-normal', 'text-13px'],
      name: 'preview_filename_space_info_label',
      text: 'Замена для пробельных символов после транслитерации ',
      type: 'label',
    },
    {
      cssClass: ['ml-6', 'font-normal', 'text-13px'],
      name: 'preview_filename_sublable_input_1',
      text: 'Количество символов: 52',
      type: 'label',
    },
    {
      cssClass: ['ml-6', 'font-normal', 'text-13px'],
      name: 'preview_filename_sublable_input_2',
      text: 'Количество слов: 6',
      type: 'label',
    },
    {
      cssClass: ['flex', 'flex-col', 'items-center'],
      fields: ['settings_images_product_title'],
      name: 'settings_images_product_block',
      type: 'div',
    },
    {
      cssClass: ['font-medium', 'text-base'],
      name: 'settings_images_product_title',
      parentClass: [
        'w-max',
        'mt-6',
        'relative',
        'before:absolute',
        'before:left-[-30px]',
        'before:top-1/2',
        'before:block',
        'before:w-5',
        'before:border-t',
        'before:border-dividerColor',
        'after:absolute',
        'after:right-[-75%]',
        'after:top-1/2',
        'after:block',
        'after:w-[75%]',
        'after:border-t',
        'after:border-dividerColor',
      ],
      text: 'Настройки картинок детали товара',
      type: 'label',
    },
    {
      cssClass: ['grid', 'grid-cols-[350px_1fr]', 'gap-2', 'pt-6'],
      fields: ['images_product_atl_lable', 'images_product_atl_inputs_fields'],
      name: 'images_product_atl_block',
      type: 'div',
    },
    {
      fields: [
        'images_product_atl_input',
        'images_product_atl_checkbox',
        'images_product_atl_sublable_input_1',
        'images_product_atl_sublable_input_2',
      ],
      name: 'images_product_atl_inputs_fields',
      type: 'div',
    },
    {
      name: 'images_product_atl_lable',
      parentClass: ['flex', 'justify-end', 'mt-2.5'],
      text: 'Шаблон ATL:',
      type: 'label',
    },
    {
      format: 'text',
      name: 'images_product_atl_input',
      parentClass: ['max-w-580', 'dots_after_input', 'relative'],
      type: 'input',
      validations: [
        {
          params: ['Это поле обязательно для заполнения'],
          type: 'required',
        },
      ],
      validationType: 'string',
      value: '',
    },
    {
      label: 'Изменить для этого раздела и его подразделов.',
      name: 'images_product_atl_checkbox',
      parentClass: ['mt-1'],
      type: 'boolean',
      value: true,
      viewType: 'checkbox',
    },
    {
      cssClass: ['ml-6', 'font-normal', 'text-13px'],
      name: 'images_product_atl_sublable_input_1',
      text: 'Количество символов: 52',
      type: 'label',
    },
    {
      cssClass: ['ml-6', 'font-normal', 'text-13px'],
      name: 'images_product_atl_sublable_input_2',
      text: 'Количество слов: 6',
      type: 'label',
    },
    {
      cssClass: ['grid', 'grid-cols-[350px_1fr]', 'gap-2', 'pt-6'],
      fields: [
        'images_product_title_lable',
        'images_product_title_inputs_fields',
      ],
      name: 'images_product_title_block',
      type: 'div',
    },
    {
      fields: [
        'images_product_title_input',
        'images_product_title_checkbox',
        'images_product_title_sublable_input_1',
        'images_product_title_sublable_input_2',
      ],
      name: 'images_product_title_inputs_fields',
      type: 'div',
    },
    {
      name: 'images_product_title_lable',
      parentClass: ['flex', 'justify-end', 'mt-2.5'],
      text: 'Шаблон TITLE:',
      type: 'label',
    },
    {
      format: 'text',
      name: 'images_product_title_input',
      parentClass: ['max-w-580', 'dots_after_input', 'relative'],
      type: 'input',
      validations: [
        {
          params: ['Это поле обязательно для заполнения'],
          type: 'required',
        },
      ],
      validationType: 'string',
      value: '',
    },
    {
      label: 'Изменить для этого раздела и его подразделов.',
      name: 'images_product_title_checkbox',
      parentClass: ['mt-1'],
      type: 'boolean',
      value: true,
      viewType: 'checkbox',
    },
    {
      cssClass: ['ml-6', 'font-normal', 'text-13px'],
      name: 'images_product_title_sublable_input_1',
      text: 'Количество символов: 52',
      type: 'label',
    },
    {
      cssClass: ['ml-6', 'font-normal', 'text-13px'],
      name: 'images_product_title_sublable_input_2',
      text: 'Количество слов: 6',
      type: 'label',
    },
    {
      cssClass: ['grid', 'grid-cols-[350px_1fr]', 'gap-2', 'pt-6'],
      fields: [
        'images_product_filename_lable',
        'images_product_filename_inputs_fields',
      ],
      name: 'images_product_filename_block',
      type: 'div',
    },
    {
      fields: [
        'images_product_filename_input',
        'images_product_filename_checkbox_1',
        'images_product_filename_checkbox_2',
        'images_product_filename_checkbox_3',
        'images_product_filename_space_info_block',
        'images_product_filename_sublable_input_1',
        'images_product_filename_sublable_input_2',
      ],
      name: 'images_product_filename_inputs_fields',
      type: 'div',
    },
    {
      name: 'images_product_filename_lable',
      parentClass: ['flex', 'justify-end', 'mt-2.5'],
      text: 'Шаблон имени файла:',
      type: 'label',
    },
    {
      format: 'text',
      name: 'images_product_filename_input',
      parentClass: ['max-w-580', 'dots_after_input', 'relative'],
      type: 'input',
      validations: [
        {
          params: ['Это поле обязательно для заполнения'],
          type: 'required',
        },
      ],
      validationType: 'string',
      value: '',
    },
    {
      label: 'Изменить для этого раздела и его подразделов.',
      name: 'images_product_filename_checkbox_1',
      parentClass: ['mt-1'],
      type: 'boolean',
      value: true,
      viewType: 'checkbox',
    },
    {
      label: 'Привести к нижнему регистру.',
      name: 'images_product_filename_checkbox_2',
      parentClass: ['mt-1'],
      type: 'boolean',
      value: true,
      viewType: 'checkbox',
    },
    {
      label: 'Транслировать.',
      name: 'images_product_filename_checkbox_3',
      parentClass: ['mt-1'],
      type: 'boolean',
      value: true,
      viewType: 'checkbox',
    },
    {
      cssClass: ['flex', 'items-center'],
      fields: [
        'images_product_filename_space_info_input',
        'images_product_filename_space_info_label',
      ],
      name: 'images_product_filename_space_info_block',
      type: 'div',
    },
    {
      format: 'text',
      name: 'images_product_filename_space_info_input',
      parentClass: ['max-w-[73px]'],
      type: 'input',
      validations: [
        {
          params: ['Это поле обязательно для заполнения'],
          type: 'required',
        },
      ],
      validationType: 'string',
      value: '-',
    },
    {
      cssClass: ['ml-6', 'font-normal', 'text-13px'],
      name: 'images_product_filename_space_info_label',
      text: 'Замена для пробельных символов после транслитерации ',
      type: 'label',
    },
    {
      cssClass: ['ml-6', 'font-normal', 'text-13px'],
      name: 'images_product_filename_sublable_input_1',
      text: 'Количество символов: 52',
      type: 'label',
    },
    {
      cssClass: ['ml-6', 'font-normal', 'text-13px'],
      name: 'images_product_filename_sublable_input_2',
      text: 'Количество слов: 6',
      type: 'label',
    },
    {
      cssClass: ['flex', 'flex-col', 'items-center'],
      fields: ['settings_images_chapter_title'],
      name: 'settings_images_chapter_block',
      type: 'div',
    },
    {
      cssClass: ['font-medium', 'text-base'],
      name: 'settings_images_chapter_title',
      parentClass: [
        'w-max',
        'mt-6',
        'relative',
        'before:absolute',
        'before:left-[-30px]',
        'before:top-1/2',
        'before:block',
        'before:w-5',
        'before:border-t',
        'before:border-dividerColor',
        'after:absolute',
        'after:right-[-75%]',
        'after:top-1/2',
        'after:block',
        'after:w-[75%]',
        'after:border-t',
        'after:border-dividerColor',
      ],
      text: 'Настройки картинок детали раздела',
      type: 'label',
    },
    {
      cssClass: ['grid', 'grid-cols-[350px_1fr]', 'gap-2', 'pt-6'],
      fields: ['images_chapter_atl_lable', 'images_chapter_atl_inputs_fields'],
      name: 'images_chapter_atl_block',
      type: 'div',
    },
    {
      fields: [
        'images_chapter_atl_input',
        'images_chapter_atl_checkbox',
        'images_chapter_atl_sublable_input_1',
        'images_chapter_atl_sublable_input_2',
      ],
      name: 'images_chapter_atl_inputs_fields',
      type: 'div',
    },
    {
      name: 'images_chapter_atl_lable',
      parentClass: ['flex', 'justify-end', 'mt-2.5'],
      text: 'Шаблон ATL:',
      type: 'label',
    },
    {
      format: 'text',
      name: 'images_chapter_atl_input',
      parentClass: ['max-w-580', 'dots_after_input', 'relative'],
      type: 'input',
      validations: [
        {
          params: ['Это поле обязательно для заполнения'],
          type: 'required',
        },
      ],
      validationType: 'string',
      value: '',
    },
    {
      label: 'Изменить для этого раздела и его подразделов.',
      name: 'images_chapter_atl_checkbox',
      parentClass: ['mt-1'],
      type: 'boolean',
      value: true,
      viewType: 'checkbox',
    },
    {
      cssClass: ['ml-6', 'font-normal', 'text-13px'],
      name: 'images_chapter_atl_sublable_input_1',
      text: 'Количество символов: 52',
      type: 'label',
    },
    {
      cssClass: ['ml-6', 'font-normal', 'text-13px'],
      name: 'images_chapter_atl_sublable_input_2',
      text: 'Количество слов: 6',
      type: 'label',
    },
    {
      cssClass: ['grid', 'grid-cols-[350px_1fr]', 'gap-2', 'pt-6'],
      fields: [
        'images_chapter_title_lable',
        'images_chapter_title_inputs_fields',
      ],
      name: 'images_chapter_title_block',
      type: 'div',
    },
    {
      fields: [
        'images_chapter_title_input',
        'images_chapter_title_checkbox',
        'images_chapter_title_sublable_input_1',
        'images_chapter_title_sublable_input_2',
      ],
      name: 'images_chapter_title_inputs_fields',
      type: 'div',
    },
    {
      name: 'images_chapter_title_lable',
      parentClass: ['flex', 'justify-end', 'mt-2.5'],
      text: 'Шаблон TITLE:',
      type: 'label',
    },
    {
      format: 'text',
      name: 'images_chapter_title_input',
      parentClass: ['max-w-580', 'dots_after_input', 'relative'],
      type: 'input',
      validations: [
        {
          params: ['Это поле обязательно для заполнения'],
          type: 'required',
        },
      ],
      validationType: 'string',
      value: '',
    },
    {
      label: 'Изменить для этого раздела и его подразделов.',
      name: 'images_chapter_title_checkbox',
      parentClass: ['mt-1'],
      type: 'boolean',
      value: true,
      viewType: 'checkbox',
    },
    {
      cssClass: ['ml-6', 'font-normal', 'text-13px'],
      name: 'images_chapter_title_sublable_input_1',
      text: 'Количество символов: 52',
      type: 'label',
    },
    {
      cssClass: ['ml-6', 'font-normal', 'text-13px'],
      name: 'images_chapter_title_sublable_input_2',
      text: 'Количество слов: 6',
      type: 'label',
    },
    {
      cssClass: ['grid', 'grid-cols-[350px_1fr]', 'gap-2', 'pt-6'],
      fields: [
        'images_chapter_filename_lable',
        'images_chapter_filename_inputs_fields',
      ],
      name: 'images_chapter_filename_block',
      type: 'div',
    },
    {
      fields: [
        'images_chapter_filename_input',
        'images_chapter_filename_checkbox_1',
        'images_chapter_filename_checkbox_2',
        'images_chapter_filename_checkbox_3',
        'images_chapter_filename_space_info_block',
        'images_chapter_filename_sublable_input_1',
        'images_chapter_filename_sublable_input_2',
      ],
      name: 'images_chapter_filename_inputs_fields',
      type: 'div',
    },
    {
      name: 'images_chapter_filename_lable',
      parentClass: ['flex', 'justify-end', 'mt-2.5'],
      text: 'Шаблон имени файла:',
      type: 'label',
    },
    {
      format: 'text',
      name: 'images_chapter_filename_input',
      parentClass: ['max-w-580', 'dots_after_input', 'relative'],
      type: 'input',
      validations: [
        {
          params: ['Это поле обязательно для заполнения'],
          type: 'required',
        },
      ],
      validationType: 'string',
      value: '',
    },
    {
      label: 'Изменить для этого раздела и его подразделов.',
      name: 'images_chapter_filename_checkbox_1',
      parentClass: ['mt-1'],
      type: 'boolean',
      value: true,
      viewType: 'checkbox',
    },
    {
      label: 'Привести к нижнему регистру.',
      name: 'images_chapter_filename_checkbox_2',
      parentClass: ['mt-1'],
      type: 'boolean',
      value: true,
      viewType: 'checkbox',
    },
    {
      label: 'Транслировать.',
      name: 'images_chapter_filename_checkbox_3',
      parentClass: ['mt-1'],
      type: 'boolean',
      value: true,
      viewType: 'checkbox',
    },
    {
      cssClass: ['flex', 'items-center'],
      fields: [
        'images_chapter_filename_space_info_input',
        'images_chapter_filename_space_info_label',
      ],
      name: 'images_chapter_filename_space_info_block',
      type: 'div',
    },
    {
      format: 'text',
      name: 'images_chapter_filename_space_info_input',
      parentClass: ['max-w-[73px]'],
      type: 'input',
      validations: [
        {
          params: ['Это поле обязательно для заполнения'],
          type: 'required',
        },
      ],
      validationType: 'string',
      value: '-',
    },
    {
      cssClass: ['ml-6', 'font-normal', 'text-13px'],
      name: 'images_chapter_filename_space_info_label',
      text: 'Замена для пробельных символов после транслитерации ',
      type: 'label',
    },
    {
      cssClass: ['ml-6', 'font-normal', 'text-13px'],
      name: 'images_chapter_filename_sublable_input_1',
      text: 'Количество символов: 52',
      type: 'label',
    },
    {
      cssClass: ['ml-6', 'font-normal', 'text-13px'],
      name: 'images_chapter_filename_sublable_input_2',
      text: 'Количество слов: 6',
      type: 'label',
    },
    {
      cssClass: ['flex', 'flex-col', 'items-center'],
      fields: ['additional_fields_title'],
      name: 'additional_fields_block',
      type: 'div',
    },
    {
      cssClass: ['font-medium', 'text-base'],
      name: 'additional_fields_title',
      parentClass: [
        'w-max',
        'mt-6',
        'relative',
        'before:absolute',
        'before:left-[-30px]',
        'before:top-1/2',
        'before:block',
        'before:w-5',
        'before:border-t',
        'before:border-dividerColor',
        'after:absolute',
        'after:right-[-75%]',
        'after:top-1/2',
        'after:block',
        'after:w-[75%]',
        'after:border-t',
        'after:border-dividerColor',
      ],
      text: 'Дополнительные поля',
      type: 'label',
    },
    {
      cssClass: ['grid', 'grid-cols-[350px_1fr]', 'gap-2', 'pt-6'],
      fields: [
        'additional_fields_containter_lable',
        'additional_fields_containter_inputs_fields',
      ],
      name: 'additional_fields_containter_block',
      type: 'div',
    },
    {
      name: 'additional_fields_containter_lable',
      parentClass: ['flex', 'justify-end', 'mt-2.5'],
      text: 'Укажите вид контейнера:',
      type: 'label',
    },
    {
      fields: ['additional_fields_containter_input'],
      name: 'additional_fields_containter_inputs_fields',
      parentClass: ['mt-2.5'],
      type: 'div',
    },
    {
      name: 'additional_fields_containter_input',
      options: [
        {
          label: 'Каталог',
          value: 'catalog',
        },
        {
          label: 'Тип',
          value: 'type',
        },
        {
          label: 'Категория',
          value: 'category',
        },
        {
          label: 'Разновидность',
          value: 'variation',
        },
      ],
      type: 'radio',
      value: 'catalog',
    },
    {
      cssClass: ['grid', 'grid-cols-[350px_1fr]', 'gap-2', 'pt-6'],
      fields: [
        'additional_fields_meta_title_lable',
        'additional_fields_meta_title_inputs_fields',
      ],
      name: 'additional_fields_meta_title_block',
      type: 'div',
    },
    {
      name: 'additional_fields_meta_title_lable',
      parentClass: ['flex', 'justify-end', 'mt-2.5'],
      text: 'Meta title для раздела:',
      type: 'label',
    },
    {
      fields: ['additional_fields_meta_title_input'],
      name: 'additional_fields_meta_title_inputs_fields',
      type: 'div',
    },
    {
      format: 'text',
      name: 'additional_fields_meta_title_input',
      parentClass: ['max-w-580', 'relative'],
      type: 'input',
      validations: [
        {
          params: ['Это поле обязательно для заполнения'],
          type: 'required',
        },
      ],
      validationType: 'string',
      value: '',
    },
    {
      cssClass: ['grid', 'grid-cols-[350px_1fr]', 'gap-2', 'pt-6'],
      fields: [
        'additional_fields_meta_desc_lable',
        'additional_fields_meta_desc_inputs_fields',
      ],
      name: 'additional_fields_meta_desc_block',
      type: 'div',
    },
    {
      name: 'additional_fields_meta_desc_lable',
      parentClass: ['flex', 'justify-end', 'mt-2.5'],
      text: 'Meta description для раздела:',
      type: 'label',
    },
    {
      fields: ['additional_fields_meta_desc_input'],
      name: 'additional_fields_meta_desc_inputs_fields',
      parentClass: ['mt-2.5'],
      type: 'div',
    },
    {
      name: 'additional_fields_meta_desc_input',
      parentClass: ['max-w-580', 'relative'],
      type: 'textarea',
      value: 'view',
    },
    {
      cssClass: ['grid', 'grid-cols-[350px_1fr]', 'gap-2', 'pt-6'],
      fields: [
        'additional_fields_parent_coollection_lable',
        'additional_fields_parent_coollection_inputs_fields',
      ],
      name: 'additional_fields_parent_coollection_block',
      type: 'div',
    },
    {
      name: 'additional_fields_parent_coollection_lable',
      parentClass: ['flex', 'justify-end', 'mt-2.5'],
      text: 'Использовать подборку родителя:',
      type: 'label',
    },
    {
      name: 'additional_fields_parent_coollection_inputs_fields',
      parentClass: ['mt-2.5'],
      type: 'boolean',
      value: true,
      viewType: 'checkbox',
    },
    {
      cssClass: ['grid', 'grid-cols-[350px_1fr]', 'gap-2', 'pt-6'],
      fields: [
        'additional_fields_product_collection_lable',
        'additional_fields_product_collection_inputs_fields',
      ],
      name: 'additional_fields_product_collection_block',
      type: 'div',
    },
    {
      fields: [
        'additional_fields_product_collection_checkbox',
        'additional_fields_product_collection_input',
      ],
      name: 'additional_fields_product_collection_inputs_fields',
      type: 'div',
    },
    {
      name: 'additional_fields_product_collection_lable',
      parentClass: ['flex', 'justify-end', 'mt-2.5'],
      text: 'Подборка товаров:',
      type: 'label',
    },
    {
      label: 'Изменить для этого раздела и его подразделов.',
      name: 'additional_fields_product_collection_checkbox',
      parentClass: ['mt-2.5'],
      type: 'boolean',
      value: true,
      viewType: 'checkbox',
    },
    {
      format: 'text',
      name: 'additional_fields_product_collection_input',
      parentClass: ['max-w-580', 'relative', 'mt-2.5'],
      type: 'input',
      validations: [
        {
          params: ['Это поле обязательно для заполнения'],
          type: 'required',
        },
      ],
      validationType: 'string',
      value: '',
    },
    {
      cssClass: ['flex', 'flex-col', 'items-center'],
      fields: ['property_title'],
      name: 'property_block',
      type: 'div',
    },
    {
      cssClass: ['font-medium', 'text-base'],
      name: 'property_title',
      parentClass: [
        'w-max',
        'mt-6',
        'relative',
        'before:absolute',
        'before:left-[-30px]',
        'before:top-1/2',
        'before:block',
        'before:w-5',
        'before:border-t',
        'before:border-dividerColor',
        'after:absolute',
        'after:right-[-75%]',
        'after:top-1/2',
        'after:block',
        'after:w-[75%]',
        'after:border-t',
        'after:border-dividerColor',
      ],
      text: 'Свойства',
      type: 'label',
    },
    {
      cssClass: ['grid', 'grid-cols-2', 'gap-x-7'],
      fields: [
        'property_product_lable',
        'property_section_lable',
        'property_weight_checkbox',
        'property_weight_text',
        'property_year_checkbox',
        'property_year_text',
        'property_equipment_checkbox',
        'property_equipment_text',
        'property_volume_checkbox',
        'property_volume_text',
        'property_size_checkbox',
        'property_size_text',
        'property_color_checkbox',
        'property_color_text',
      ],
      name: 'property_columns_block',
      parentClass: ['mt-2.5', 'flex', 'justify-center'],
      text: 'Свойства товаров:',
      type: 'div',
    },
    {
      name: 'property_product_lable',
      text: 'Свойства товаров:',
      type: 'label',
    },
    {
      name: 'property_section_lable',
      text: 'Свойства раздела:',
      type: 'label',
    },
    {
      containerClass: ['border-b border-[rgba(0, 0, 0, 0.06)]', 'p-1'],
      name: 'property_weight_checkbox',
      title: 'Вес',
      titlePosition: 'right',
      type: 'boolean',
      value: false,
      viewType: 'checkbox',
    },
    {
      name: 'property_weight_text',
      parentClass: ['border-b border-[rgba(0, 0, 0, 0.06)]', 'p-1'],
      text: 'Вес',
      type: 'label',
    },
    {
      containerClass: ['border-b border-[rgba(0, 0, 0, 0.06)]', 'p-1'],
      name: 'property_year_checkbox',
      title: 'Год производства',
      titlePosition: 'right',
      type: 'boolean',
      value: false,
      viewType: 'checkbox',
    },
    {
      name: 'property_year_text',
      parentClass: ['border-b border-[rgba(0, 0, 0, 0.06)]', 'p-1'],
      text: 'Год производства',
      type: 'label',
    },
    {
      containerClass: ['border-b border-[rgba(0, 0, 0, 0.06)]', 'p-1'],
      name: 'property_equipment_checkbox',
      title: 'Комплектация',
      titlePosition: 'right',
      type: 'boolean',
      value: false,
      viewType: 'checkbox',
    },
    {
      name: 'property_equipment_text',
      parentClass: ['border-b border-[rgba(0, 0, 0, 0.06)]', 'p-1'],
      text: 'Комплектация',
      type: 'label',
    },
    {
      containerClass: ['border-b border-[rgba(0, 0, 0, 0.06)]', 'p-1'],
      name: 'property_volume_checkbox',
      title: 'Объем',
      titlePosition: 'right',
      type: 'boolean',
      value: false,
      viewType: 'checkbox',
    },
    {
      name: 'property_volume_text',
      parentClass: ['border-b border-[rgba(0, 0, 0, 0.06)]', 'p-1'],
      text: 'Объем',
      type: 'label',
    },
    {
      containerClass: ['border-b border-[rgba(0, 0, 0, 0.06)]', 'p-1'],
      name: 'property_size_checkbox',
      title: 'Размер',
      titlePosition: 'right',
      type: 'boolean',
      value: false,
      viewType: 'checkbox',
    },
    {
      name: 'property_size_text',
      parentClass: ['border-b border-[rgba(0, 0, 0, 0.06)]', 'p-1'],
      text: 'Размер',
      type: 'label',
    },
    {
      containerClass: ['border-b border-[rgba(0, 0, 0, 0.06)]', 'p-1'],
      name: 'property_color_checkbox',
      title: 'Цвет',
      titlePosition: 'right',
      type: 'boolean',
      value: false,
      viewType: 'checkbox',
    },
    {
      name: 'property_color_text',
      parentClass: ['border-b border-[rgba(0, 0, 0, 0.06)]', 'p-1'],
      text: 'Цвет',
      type: 'label',
    },
    {
      cssClass: ['grid', 'grid-cols-[350px_1fr]', 'gap-2', 'pt-6'],
      fields: [
        'additional_fields_hidden_filters_lable',
        'additional_fields_hidden_filters_inputs_fields',
      ],
      name: 'additional_fields_hidden_filters_block',
      type: 'div',
    },
    {
      name: 'additional_fields_hidden_filters_lable',
      parentClass: ['flex', 'justify-end', 'mt-2.5'],
      text: 'Meta title для раздела:',
      type: 'label',
    },
    {
      fields: ['additional_fields_hidden_filters_input'],
      name: 'additional_fields_hidden_filters_inputs_fields',
      type: 'div',
    },
    {
      format: 'text',
      name: 'additional_fields_hidden_filters_input',
      parentClass: ['max-w-580', 'relative'],
      type: 'input',
      validations: [
        {
          params: ['Это поле обязательно для заполнения'],
          type: 'required',
        },
      ],
      validationType: 'string',
      value: '',
    },
    {
      name: 'search_tags_inputs_fields',
      type: 'div',
      fields: ['search_tags_input'],
    },
    {
      name: 'search_tags_labels_block',
      type: 'div',
      cssClass: ['text-end'],
      fields: ['search_tags_lable', 'search_tags_sublable'],
    },
    {
      text: 'Поисковые теги:',
      name: 'search_tags_lable',
      type: 'label',
    },
    {
      text: 'введите слова или словосочетания, разделяя их запятыми',
      name: 'search_tags_sublable',
      type: 'label',
      cssClass: ['text-xs'],
    },
    {
      name: 'search_tags_input',
      format: 'text',
      value: '',
      type: 'input',
      parentClass: ['max-w-580', 'dots_after_input', 'relative'],
    },
    {
      name: 'seo_tab__buttons_container_block',
      type: 'div',
      cssClass: ['flex', 'gap-2', 'mt-8', 'pb-10', 'ml-85'],
      fields: ['seo_tab__cancel_button', 'seo_tab__save_button'],
    },
    {
      type: 'button',
      value: 'Сохранить',
      name: 'seo_tab__save_button',
      size: 'large',
      buttonType: 'primary',
      handlers: [
        {
          name: 'pushData',
          params: {
            pageName: 'catalog_edit',
            blockName: 'seo_tab__body_block_1',
            endpoint: 'https://ekat.sergeivl.ru/api/tests/request',
          },
        },
        {
          name: 'resetBlockData',
          params: {
            pageName: 'catalog_edit',
            blockName: 'seo_tab__body_block_1',
          },
        },
      ],
    },
    {
      type: 'button',
      value: 'Отмена',
      name: 'seo_tab__cancel_button',
      size: 'large',
      buttonType: 'default',
      disabled: false,
    },
    {
      name: 'offers__container_block',
      type: 'div',
      cssClass: ['bg-white'],
      fields: ['offers__body_block'],
    },
    {
      name: 'offers__body_block',
      type: 'div',
      cssClass: ['p-6'],
      fields: ['offers__table'],
    },
    {
      name: 'offers__table',
      type: 'table',
      config: {
        pagination: true,
        size: 'small',
        align: 'center',
        bordered: true,
      },
      data: [
        {
          offer: {
            title: 'Samsung galaxy',
            link: '/mikes',
            offerInfo: [
              { param: 'Экран', value: '6.7 (2778х1284) OLED 120Гц' },
              { param: 'Встроенная память', value: '128 гБ' },
              { param: 'Оперативная память', value: '6ГБ' },
              { param: 'З камеры', value: '12 МП, 12 МП, 12 мп' },
              { param: 'Аккумулятор', value: '4352 мАч' },
            ],
          },
          shop: 'Все смартфоны',
          status: 2,
        },
        {
          offer: {
            title: 'Sony Playstation 5',
            link: '/mikes',
            offerInfo: [
              { param: 'Экран', value: '6.7 (2778х1284) OLED 120Гц' },
              { param: 'Встроенная память', value: '128 гБ' },
              { param: 'Оперативная память', value: '6ГБ' },
              { param: 'З камеры', value: '12 МП, 12 МП, 12 мп' },
              { param: 'Аккумулятор', value: '4352 мАч' },
            ],
          },
          shop: 'Все приставки',
          status: 0,
        },
        {
          offer: {
            title: 'Iphone',
            link: '/mikes',
            offerInfo: [
              { param: 'Экран', value: '6.7 (2778х1284) OLED 120Гц' },
              { param: 'Встроенная память', value: '128 гБ' },
              { param: 'Оперативная память', value: '6ГБ' },
              { param: 'З камеры', value: '12 МП, 12 МП, 12 мп' },
              { param: 'Аккумулятор', value: '4352 мАч' },
            ],
          },
          shop: 'Все смартфоны',
          status: 1,
        },
        {
          offer: {
            title: 'Samsung galaxy',
            link: '/mikes',
            offerInfo: [
              { param: 'Экран', value: '6.7 (2778х1284) OLED 120Гц' },
              { param: 'Встроенная память', value: '128 гБ' },
              { param: 'Оперативная память', value: '6ГБ' },
              { param: 'З камеры', value: '12 МП, 12 МП, 12 мп' },
              { param: 'Аккумулятор', value: '4352 мАч' },
            ],
          },
          shop: 'Все смартфоны',
          status: 2,
        },
        {
          offer: {
            title: 'Sony Playstation 5',
            link: '/mikes',
            offerInfo: [
              { param: 'Экран', value: '6.7 (2778х1284) OLED 120Гц' },
              { param: 'Встроенная память', value: '128 гБ' },
              { param: 'Оперативная память', value: '6ГБ' },
              { param: 'З камеры', value: '12 МП, 12 МП, 12 мп' },
              { param: 'Аккумулятор', value: '4352 мАч' },
            ],
          },
          shop: 'Все приставки',
          status: 0,
        },
        {
          offer: {
            title: 'Iphone',
            link: '/mikes',
            offerInfo: [
              { param: 'Экран', value: '6.7 (2778х1284) OLED 120Гц' },
              { param: 'Встроенная память', value: '128 гБ' },
              { param: 'Оперативная память', value: '6ГБ' },
              { param: 'З камеры', value: '12 МП, 12 МП, 12 мп' },
              { param: 'Аккумулятор', value: '4352 мАч' },
            ],
          },
          shop: 'Все смартфоны',
          status: 1,
        },
      ],
      columns: [
        {
          title: 'Оффер',
          dataIndex: 'offer',
          key: 'offer',
          resizable: true,
          widget: {
            name: 'popover',
            type: 'columns',
          },
          width: 150,
        },
        {
          title: 'Магазин',
          dataIndex: 'shop',
          key: 'shop',
          widget: {
            name: 'text',
          },
          resizable: true,
          width: 150,
          editable: false,
        },
        {
          title: 'Статус',
          dataIndex: 'status',
          key: 'status',
          resizable: true,
          widget: {
            name: 'select',
            type: 'status',
            params: [
              { id: 0, value: 'Одобрено', color: '#87D068' },
              {
                id: 1,
                value: 'Модерация',
                color: '#E6E6E6',
                textColor: '#8c8c8c',
              },
              { id: 2, value: 'Отказано', color: '#FF4D4F' },
            ],
          },
          width: 150,
        },
        {
          title: 'Действия',
          dataIndex: 'actions',
          widget: {
            name: 'actions',
          },
          width: 20,
          hide: false,
          delete: true,
          edit: true,
          copy: true,
        },
      ],
    },
  ],
}
