export default {
  title: 'Жалобы на товар',
  page: 'complaint_form_edit',
  groups: [
    {
      name: 'complaint_form_edit',
      fields: ['title_block', 'body_block'],
    },
  ],
  fields: [
    {
      name: 'title_block',
      type: 'div',
      cssClass: ['bg-white', 'p-6', 'mb-6', 'flex-col'],
      fields: ['breadcrumbs', 'title_wrap'],
    },
    {
      name: 'breadcrumbs',
      type: 'breadcrumbs',
      options: [
        {
          title: 'Главная',
          path: '/',
        },
        {
          title: 'Сервисы',
        },
        {
          title: 'Beб-формы',
        },
        {
          title: 'Тикеты',
        },
        {
          title: 'Жалобы на товар',
          path: '/main/complaints',
        },
        {
          title: 'Жалоба',
        },
      ],
    },
    {
      name: 'title_wrap',
      type: 'div',
      cssClass: ['flex', 'mt-4'],
      fields: ['title_arrow_back', 'title'],
    },
    {
      type: 'button',
      name: 'title_arrow_back',
      buttonType: 'text',
      disabled: false,
      cssClass: ['font-medium', 'text-xl', 'mr-2'],
      icon: {
        name: 'fa-solid fa-arrow-left',
      },
      handlers: [
        {
          name: 'goBack',
        },
      ],
    },
    {
      text: 'Редактирование результата заполнения веб-формы',
      name: 'title',
      type: 'label',
      cssClass: ['font-medium', 'text-xl'],
    },
    {
      name: 'body_block',
      type: 'div',
      cssClass: ['bg-white', 'flex', 'justify-center'],
      fields: ['wrapper_block'],
    },
    {
      name: 'wrapper_block',
      type: 'div',
      cssClass: ['w-600', 'p-6'],
      fields: [
        'common_info_title',
        'common_info_block',
        'results_title',
        'results_block',
      ],
    },
    {
      text: 'Общая информация',
      name: 'common_info_title',
      type: 'label',
      parentClass: [
        'mt-2.5',
        'mb-8',
        'ml-20',
        'pl-12',
        'relative',
        'before:absolute',
        'before:left-2',
        'before:top-1/2',
        'before:block',
        'before:w-5',
        'before:border-t',
        'before:border-dividerColor',
        'after:absolute',
        'after:right-0',
        'after:top-1/2',
        'after:block',
        'after:w-2/4',
        'after:border-t',
        'after:border-dividerColor',
      ],
      cssClass: ['font-semibold', 'text-base'],
    },
    {
      name: 'common_info_block',
      type: 'div',
      fields: [
        'common_info_cols_wrap',
        'common_info_status',
        'common_info_category',
      ],
    },
    {
      name: 'common_info_cols_wrap',
      type: 'div',
      cssClass: ['flex'],
      fields: ['common_info_block_col_1', 'common_info_block_col_2'],
    },
    {
      name: 'common_info_block_col_1',
      type: 'div',
      cssClass: ['flex', 'flex-col', 'items-end', 'mr-3'],
      fields: [
        'common_info_label_1',
        'common_info_label_2',
        'common_info_label_3',
        'common_info_label_4',
        'common_info_label_5',
      ],
    },
    {
      name: 'common_info_block_col_2',
      type: 'div',
      cssClass: ['flex', 'flex-col'],
      fields: [
        'common_info_text_1',
        'common_info_text_2',
        'common_info_text_3',
        'common_info_text_4',
        'common_info_text_5',
      ],
    },
    {
      text: 'Форма:',
      name: 'common_info_label_1',
      type: 'label',
      parentClass: ['mb-6'],
    },
    {
      text: '[9] Жалобы (Complaint)',
      name: 'common_info_text_1',
      type: 'link',
      parentClass: ['mb-6'],
    },
    {
      text: 'Создатель:',
      name: 'common_info_label_2',
      type: 'label',
      parentClass: ['mb-6'],
    },
    {
      text: 'Не зарегестрирован',
      name: 'common_info_text_2',
      type: 'label',
      parentClass: ['mb-6'],
    },
    {
      text: 'Создан:',
      name: 'common_info_label_3',
      type: 'label',
      parentClass: ['mb-6'],
    },
    {
      text: '23.05.2022   17:11:11',
      name: 'common_info_text_3',
      type: 'label',
      parentClass: ['mb-6'],
    },
    {
      text: 'Изменен:',
      name: 'common_info_label_4',
      type: 'label',
      parentClass: ['mb-6'],
    },
    {
      text: '23.05.2022   17:11:11',
      name: 'common_info_text_4',
      type: 'label',
      parentClass: ['mb-6'],
    },
    {
      title: 'Статус',
      titlePosition: 'left',
      description: '',
      name: 'common_info_status',
      type: 'select',
      parentClass: ['mb-6'],
      cssClass: ['w-[500px]'],
      value: 1,
      options: [
        { id: 0, name: 'Обработано' },
        { id: 1, name: 'В работе' },
        { id: 2, name: 'Отказано' },
      ],
    },
    {
      title: 'Категория',
      titlePosition: 'left',
      description: '',
      name: 'common_info_category',
      type: 'select',
      cssClass: ['w-[500px]'],
      parentClass: ['mb-6'],
      value: 1,
      options: [
        { id: 0, name: 'SonyPlayStation' },
        { id: 1, name: 'samsung' },
        { id: 2, name: 'xiaomi' },
      ],
    },
    {
      text: 'Поля результата',
      name: 'results_title',
      type: 'label',
      parentClass: [
        'mt-16',
        'mb-10',
        'ml-20',
        'pl-12',
        'relative',
        'before:absolute',
        'before:left-2',
        'before:top-1/2',
        'before:block',
        'before:w-5',
        'before:border-t',
        'before:border-dividerColor',
        'after:absolute',
        'after:right-0',
        'after:top-1/2',
        'after:block',
        'after:w-7/12',
        'after:border-t',
        'after:border-dividerColor',
      ],
      cssClass: ['font-semibold', 'text-base'],
    },
    {
      name: 'results_block',
      type: 'div',
      fields: [
        'complaint_text',
        'complaint_phone',
        'complaint_email',
        'product_number_wrap',
        'complaint_files',
        'buttons_wrap',
      ],
    },
    {
      title: 'Текст жалобы',
      titlePosition: 'left',
      name: 'complaint_text',
      type: 'textarea',
      minRows: 4,
      value: '',
      parentClass: ['mb-6', 'w-[500px]'],
    },
    {
      title: 'Телефон',
      titlePosition: 'left',
      description: '+7 (999) 766-98-09',
      name: 'complaint_phone',
      type: 'input',
      format: 'text',
      value: '',
      mask: '+7 (###) ###-##-##',
      parentClass: ['mb-6', 'w-[500px]'],
    },
    {
      title: 'E-mail',
      titlePosition: 'left',
      name: 'complaint_email',
      type: 'input',
      format: 'text',
      value: '',
      parentClass: ['mb-6', 'w-[500px]'],
    },
    {
      name: 'product_number_wrap',
      type: 'div',
      cssClass: ['flex'],
      fields: ['product_number_col_1', 'product_number_col_2'],
    },
    {
      name: 'product_number_col_1',
      type: 'div',
      cssClass: ['ml-3-neg'],
      fields: ['product_number_label'],
    },
    {
      name: 'product_number_col_2',
      type: 'div',
      cssClass: ['ml-3'],
      fields: ['product_number'],
    },
    {
      text: 'Номер заказа:',
      name: 'product_number_label',
      type: 'label',
      parentClass: ['mb-6'],
    },
    {
      text: 'Sony Playstation 5 + игра',
      name: 'product_number',
      type: 'link',
      parentClass: ['mb-6'],
    },
    {
      title: 'Файлы',
      titlePosition: 'left',
      name: 'complaint_files',
      type: 'file',
      parentClass: ['mb-6', 'w-[500px]'],
    },
    {
      name: 'buttons_wrap',
      type: 'div',
      cssClass: ['flex', 'pl-10', 'ml-12', 'mb-6'],
      fields: ['button_reset', 'button_save'],
    },
    {
      type: 'button',
      value: 'Отмена',
      name: 'button_reset',
      disabled: false,
      cssClass: ['mr-2'],
      handler: {
        name: 'resetForm',
        params: {},
      },
    },
    {
      type: 'button',
      value: 'Сохранить',
      name: 'button_save',
      buttonType: 'primary',
      disabled: false,
      handler: {
        name: 'save',
        params: {},
      },
    },
  ],
}
