export default {
  page: 'edit_banner_one',
  title: 'Редактирование баннера',
  useId: {
    endpoint: '/banners',
  },
  useTitle: {
    title: 'Редактирование баннера',
    breadcrumbs: [
      {
        title: 'Главная',
        path: '/',
      },
      {
        title: 'Контент',
      },
      {
        title: 'Баннеры',
        path: '/main/banner_list',
      },
    ],
    operations: [
      {
        text: 'Копировать',
        icon: 'fa-copy',
        handlers: [],
      },
      {
        text: 'Удалить',
        type: 'danger',
        ghost: true,
        icon: 'fa-trash',
        handlers: [
          {
            name: 'deleteFromId',
            params: {
              endpoint: 'deleteBanner',
              redirect: '/main/banner_list',
            },
          },
        ],
      },
    ],
  },
  groups: [
    {
      name: 'edit_baner_tab',
      fields: ['edit_banner__title_block', 'edit_banner__container_block'],
    },
  ],
  fields: [
    {
      name: 'edit_banner__title_block',
      type: 'div',
      style: {},
      cssClass: ['bg-white', 'p-6', 'border-b', 'border-borderColor'],
      fields: ['title_1'],
    },
    {
      text: 'Баннер',
      name: 'title_1',
      type: 'label',
      cssClass: ['font-medium', 'text-base'],
    },
    {
      name: 'edit_banner__container_block',
      type: 'div',
      style: {},
      cssClass: ['bg-white', 'p-6'],
      fields: ['edit_banner__body_block'],
    },
    {
      name: 'edit_banner__body_block',
      type: 'div',
      cssClass: ['flex', 'gap-6', 'flex-col', 'w-[800px]', 'ml-[8vw]'],
      fields: [
        'banner_type_text',
        'id_text',
        'button1',
        'create_text',
        'updated_text',
        'active_switch',
        'title_name_input',
        'sort_input',
        'link_input',
        'edit_banner_block1',
      ],
    },
    {
      title: 'Тип баннера',
      titlePosition: 'left',
      titleClass: ['flex', 'items-center'],
      text: 'Прямоугольные баннеры',
      name: 'banner_type_text',
      type: 'label',
      parentClass: ['w-500', 'font-medium'],
    },
    {
      title: 'ID',
      titlePosition: 'left',
      titleClass: ['flex', 'items-center'],
      text: '0',
      externalValue: true,
      name: 'id_text',
      type: 'label',
      parentClass: ['w-500', 'font-medium'],
    },
    {
      title: 'Создан',
      titlePosition: 'left',
      titleClass: ['flex', 'items-center'],
      text: '23.05.2022   17:11:11  Алексей',
      name: 'create_text',
      type: 'label',
      parentClass: ['w-500', 'font-medium'],
    },
    {
      title: 'Изменён',
      titlePosition: 'left',
      titleClass: ['flex', 'items-center'],
      text: '24.05.2022   16:11:11  Алексей',
      name: 'updated_text',
      type: 'label',
      parentClass: ['w-500', 'font-medium'],
    },
    {
      title: 'Активный',
      titlePosition: 'left',
      titleClass: ['flex', 'items-center'],
      name: 'active_switch',
      value: true,
      type: 'boolean',
      viewType: 'switch',
      parentClass: ['w-500'],
    },
    {
      title: 'Название',
      titlePosition: 'left',
      titleClass: ['h-10', 'flex', 'items-center'],
      description: '',
      required: false,
      name: 'title_name_input',
      format: 'text',
      value: 'Sony Playstation 5',
      type: 'input',
      parentClass: ['w-500'],
    },
    {
      title: 'Сортировка',
      titlePosition: 'left',
      titleClass: ['h-10', 'flex', 'items-center'],
      name: 'sort_input',
      format: 'text',
      value: '11111',
      type: 'input',
      parentClass: ['w-500'],
    },
    {
      title: 'Ссылка',
      titlePosition: 'left',
      titleClass: ['h-10', 'flex', 'items-center'],
      name: 'link_input',
      format: 'text',
      value: '500',
      type: 'input',
      parentClass: ['w-500'],
    },

    {
      name: 'edit_banner_block1',
      type: 'div',
      cssClass: 'flex items-start gap-x-2 ml-[8vw]',
      parentClass: ['justify-end grid grid-cols-[max-content_max-content]'],
      fields: ['edit_banner_block__content1'],
    },

    {
      name: 'edit_banner_block__content1',
      type: 'div',
      parentClass: ['w-500 mb-6'],
      fields: ['block__content1_uploadD', 'block__content1_uploadM'],
    },

    {
      title: 'Декстопное изображение',
      titlePosition: 'top',
      name: 'block__content1_uploadD',
      type: 'file',
      fileType: 'picture',
    },
    {
      title: 'Мобильное изображение',
      titlePosition: 'top',
      name: 'block__content1_uploadM',
      type: 'file',
      fileType: 'picture',
    },
  ],
}
