export default {
  page: 'legal_entity_edit',
  title: 'Редактирование юр. лица',
  useTitle: {
    title: 'Редактирование юр. лица',
    operations: [
      {
        text: 'Удалить юр. лицо',
        type: 'danger',
        icon: 'fa-solid fa-trash',
        ghost: true,
      },
    ],
    breadcrumbs: [
      {
        title: 'Главная',
        path: '/',
      },
      {
        title: 'Настройки',
      },
      {
        title: 'Базовые настройки',
        path: '/main/base_settings',
      },
      {
        title: 'Редактирование юр. лица',
        path: '/main/legal_entity_edit',
      },
    ],
  },
  groups: [
    {
      name: 'legal_entity_edit',
      fields: ['legal_entity_edit__container_block'],
    },
  ],
  fields: [
    {
      name: 'legal_entity_edit__container_block',
      type: 'div',
      cssClass: ['bg-white', 'p-6', 'mb-12'],
      fields: ['legal_entity_edit__body_block'],
    },
    {
      name: 'legal_entity_edit__body_block',
      type: 'div',
      cssClass: ['flex', 'gap-6', 'flex-col', 'w-[750px]', 'ml-[220px]'],
      fields: [
        'legal_entity_edit__body_block__title_name_input',
        'legal_entity_edit__body_block__ogrn_input',
        'legal_entity_edit__body_block__inn_input',
        'legal_entity_edit__body_block__kpp_input',
        'legal_entity_edit__body_block__legal_address_input',
        'legal_entity_edit__body_block__fact_address_input',
        'legal_entity_edit__body_block__bank_name_input',
        'legal_entity_edit__body_block__bik_bank_input',
        'legal_entity_edit__body_block__number_kor_bank_account_input',
        'legal_entity_edit__body_block__number_bank_check_organisation_input',
        'legal_entity_edit__body_block__boss_organisation_name_input',
        'legal_entity_edit__buttons_container_block',
      ],
    },
    {
      title: 'Название организации',
      titlePosition: 'left',
      titleClass: ['h-10', 'flex', 'items-center'],
      description: '',
      name: 'legal_entity_edit__body_block__title_name_input',
      format: 'text',
      value: '',
      type: 'input',
      parentClass: ['w-500'],
      validation: {
        type: 'string',
        rules: [
          {
            type: 'required',
          },
        ],
      },
    },
    {
      title: 'ОГРН',
      titlePosition: 'left',
      titleClass: ['h-10', 'flex', 'items-center'],
      description: '',
      name: 'legal_entity_edit__body_block__ogrn_input',
      format: 'text',
      value: '',
      type: 'input',
      parentClass: ['w-500'],
    },
    {
      title: 'ИНН',
      titlePosition: 'left',
      titleClass: ['h-10', 'flex', 'items-center'],
      description: '',
      name: 'legal_entity_edit__body_block__inn_input',
      format: 'text',
      value: '',
      type: 'input',
      parentClass: ['w-500'],
      validation: {
        type: 'string',
        rules: [
          {
            type: 'required',
          },
        ],
      },
    },
    {
      title: 'КПП',
      titlePosition: 'left',
      titleClass: ['h-10', 'flex', 'items-center'],
      description: '',
      name: 'legal_entity_edit__body_block__kpp_input',
      format: 'text',
      value: '',
      type: 'input',
      parentClass: ['w-500'],
    },
    {
      title: 'Юридический адрес',
      titlePosition: 'left',
      titleClass: ['h-10', 'flex', 'items-center'],
      description: '',
      name: 'legal_entity_edit__body_block__legal_address_input',
      format: 'text',
      value: '',
      type: 'input',
      parentClass: ['w-500'],
      validation: {
        type: 'string',
        rules: [
          {
            type: 'required',
          },
        ],
      },
    },
    {
      title: 'Фактический адрес',
      titlePosition: 'left',
      titleClass: ['h-10', 'flex', 'items-center'],
      description: '',
      name: 'legal_entity_edit__body_block__fact_address_input',
      format: 'text',
      value: '',
      type: 'input',
      parentClass: ['w-500'],
    },
    {
      title: 'Название банка',
      titlePosition: 'left',
      titleClass: ['h-10', 'flex', 'items-center'],
      description: '',
      name: 'legal_entity_edit__body_block__bank_name_input',
      format: 'text',
      value: '',
      type: 'input',
      parentClass: ['w-500'],
    },
    {
      title: 'БИК',
      titlePosition: 'left',
      titleClass: ['h-10', 'flex', 'items-center'],
      description: '',
      name: 'legal_entity_edit__body_block__bik_bank_input',
      format: 'text',
      value: '',
      type: 'input',
      parentClass: ['w-500'],
    },
    {
      title: 'Номер корр. счёта банка',
      titlePosition: 'left',
      titleClass: ['h-10', 'flex', 'items-center'],
      description: '',
      name: 'legal_entity_edit__body_block__number_kor_bank_account_input',
      format: 'text',
      value: '',
      type: 'input',
      parentClass: ['w-500'],
    },
    {
      title: 'Номер банковского счета организации',
      titlePosition: 'left',
      titleClass: ['h-10', 'flex', 'items-center'],
      description: '',
      name: 'legal_entity_edit__body_block__number_bank_check_organisation_input',
      format: 'text',
      value: '',
      type: 'input',
      parentClass: ['w-500'],
      validation: {
        type: 'string',
        rules: [
          {
            type: 'required',
          },
        ],
      },
    },
    {
      title: 'ФИО руководителя',
      titlePosition: 'left',
      titleClass: ['h-10', 'flex', 'items-center'],
      description: '',
      name: 'legal_entity_edit__body_block__boss_organisation_name_input',
      format: 'text',
      value: '',
      type: 'input',
      parentClass: ['w-500'],
    },
    {
      name: 'legal_entity_edit__buttons_container_block',
      type: 'div',
      cssClass: ['flex', 'gap-2.5', 'ml-[253px]'],
      fields: [
        'legal_entity_edit__cancel_button',
        'legal_entity_edit__save_button',
      ],
    },
    {
      type: 'button',
      value: 'Сохранить',
      name: 'legal_entity_edit__save_button',
      size: 'large',
      buttonType: 'primary',
      handlers: [
        {
          name: 'pushData',
          params: {
            pageName: 'legal_entity_edit',
            blockName: 'legal_entity_edit__container_block',
          },
        },
      ],
    },
    {
      type: 'button',
      value: 'Отмена',
      name: 'legal_entity_edit__cancel_button',
      size: 'large',
      buttonType: 'default',
    },
  ],
}
