export default {
  page: 'profile',
  groups: [
    {
      name: 'profile',
      layoutForm: 'vertical',
      fields: ['main_block'],
    },
  ],
  fields: [
    {
      layout: 'grid',
      name: 'main_block',
      type: 'div',
      fields: ['title_block', 'body_block'],
    },
    {
      name: 'title_block',
      type: 'div',
      cssClass: ['bg-white', 'p-6'],
      style: {},
      fields: ['title'],
    },
    {
      text: 'Профиль',
      name: 'title',
      type: 'label',
      cssClass: ['font-medium', 'text-xl'],
      style: {},
    },
    {
      name: 'body_block',
      type: 'div',
      cssClass: [
        'bg-borderColor',
        'py-6',
        'rounded-xl',
        'grid-cols-2',
        'auto-rows-fr',
        'auto-cols-fr',
        'gap-x-6',
        'gap-y-0',
        'grid',
        'justify-end',
      ],
      style: {},
      fields: ['profile_block', 'history_block'],
    },
    {
      name: 'profile_block',
      type: 'div',
      cssClass: ['bg-white'],
      style: {},
      fields: ['profile_header', 'profile_body'],
    },
    {
      name: 'profile_header',
      type: 'div',
      cssClass: [
        'px-6',
        'py-5',
        'border-b',
        'border-solid',
        'border-borderColor',
        'h-18',
      ],
      style: {},
      fields: ['profile_label'],
    },
    {
      text: 'Личные данные',
      name: 'profile_label',
      type: 'label',
      cssClass: ['font-medium', 'text-base'],
      style: {},
    },
    {
      name: 'profile_body',
      type: 'div',
      fields: ['profile_data'],
    },
    {
      name: 'profile_data',
      type: 'div',
      cssClass: ['flex', 'p-6', 'gap-10'],
      style: {},
      fields: ['labels', 'data'],
    },
    {
      name: 'labels',
      type: 'div',
      fields: [
        'fio_label',
        'mail_label',
        'role_label',
        'date_create_label',
        'last_login_label',
      ],
    },
    {
      text: 'Имя фамилия',
      name: 'fio_label',
      type: 'label',
      cssClass: ['text-textSecondary', 'leading-9'],
      style: {},
    },
    {
      text: 'Email',
      name: 'mail_label',
      type: 'label',
      cssClass: ['text-textSecondary', 'leading-9'],
      style: {},
    },
    {
      text: 'Роль',
      name: 'role_label',
      type: 'label',
      cssClass: ['text-textSecondary', 'leading-9'],
      style: {},
    },
    {
      text: 'Профиль создан',
      name: 'date_create_label',
      type: 'label',
      cssClass: ['text-textSecondary', 'leading-9'],
      style: {},
    },
    {
      text: 'Последний логин',
      name: 'last_login_label',
      type: 'label',
      cssClass: ['text-textSecondary', 'leading-9'],
      style: {},
    },
    {
      name: 'data',
      type: 'div',
      fields: [
        'fio_data',
        'mail_data',
        'role_data',
        'date_create_data',
        'last_login_data',
      ],
    },
    {
      text: 'Admin',
      name: 'fio_data',
      type: 'label',
      cssClass: ['leading-9'],
      style: {},
    },
    {
      text: 'admin@mail.ru',
      name: 'mail_data',
      type: 'label',
      cssClass: ['leading-9'],
      style: {},
    },
    {
      text: 'Админ',
      name: 'role_data',
      type: 'label',
      cssClass: ['leading-9'],
      style: {},
    },
    {
      text: '14.10.2022',
      name: 'date_create_data',
      type: 'label',
      cssClass: ['leading-9'],
      style: {},
    },
    {
      text: '14.10.2022',
      name: 'last_login_data',
      type: 'label',
      cssClass: ['leading-9'],
      style: {},
    },
    {
      name: 'history_block',
      type: 'div',
      cssClass: ['bg-white'],
      style: {},
      fields: ['history_header', 'history_body'],
    },
    {
      name: 'history_header',
      type: 'div',
      fields: ['history_label', 'history_date'],
      cssClass: [
        'px-6',
        'py-5',
        'border-b',
        'border-solid',
        'border-borderColor',
        'h-18',
        'flex',
        'justify-between',
      ],
      style: {},
    },
    {
      text: 'История',
      name: 'history_label',
      type: 'label',
      cssClass: ['font-medium', 'text-base'],
      style: {},
    },
    {
      name: 'history_date',
      required: false,
      value: [],
      type: 'datetime',
      range: true,
      displayFormat: 'YYYY-MM-DD',
      format: 'YYYY-MM-DD',
      mode: 'date',
    },
    {
      name: 'history_body',
      type: 'div',
      fields: ['history'],
      cssClass: ['p-6'],
      style: {},
    },
    {
      name: 'history',
      type: 'timeline',
      items: [
        {
          date: '2022-14-10 12:22',
          action:
            'отредактировал(а) h1, text, image, source_published, для vxbvf ',
        },
        {
          date: '2022-14-10 12:22',
          action:
            'отредактировал(а) h1, text, image, source_published, для vxbvf ',
        },
        {
          date: '2022-14-10 12:22',
          action:
            'отредактировал(а) h1, text, image, source_published, для vxbvf ',
        },
      ],
    },
  ],
}
