export default {
  page: 'rates',
  title: 'Реквизиты',
  groups: [
    {
      name: 'rates',
      fields: ['title_block', 'body_block'],
    },
  ],
  fields: [
    {
      name: 'title_block',
      type: 'div',
      cssClass: [
        'p-6',
        'bg-white',
        'flex',
        'gap-2',
        'items-end',
        'border-b-solid',
        'border-b-2',
        'border-b-#f5f5f5',
      ],
      fields: ['title', 'link'],
    },
    {
      text: 'Ставки',
      name: 'title',
      type: 'label',
      cssClass: ['font-medium', 'text-xl', 'leading-5'],
    },
    {
      name: 'body_block',
      type: 'div',
      cssClass: ['bg-white'],
      fields: ['table_block'],
    },
    {
      name: 'table_block',
      type: 'div',
      cssClass: ['p-6'],
      fields: ['table'],
    },
    {
      name: 'table',
      type: 'table',
      config: {
        pagination: false,
        size: 'small',
        align: 'center',
        gap: '4',
        bordered: true,
        selection: true,
        search: [
          {
            name: 'my_rates_filter',
            type: 'checkbox',
            fields: ['my_rates'],
            label: 'Мои ставки',
            infoTooltip: 'Мои ставки',
          },
          {
            name: 'search_feed',
            type: 'select',
            fields: ['feed'],
            filterWidth: '230px',
            filterMultiple: true,
            filterTitle: 'Отфильтровать по фидам',
          },
        ],
        filtersPosition: [
          'category',
          'price',
          'offer',
          'my_rates_filter',
          'search_feed',
        ],
      },

      data: [
        {
          category: 'Смартфон',
          offer: 'Honor',
          price: 1000,
          city: 'Санкт-Петербург',
          placement: 'Страница товара',
          recommendations: 800,
          rate: 400,
          my_rates: true,
          feed: 'Телефоны Москва',
        },
        {
          category: 'Игровая приставка',
          offer: 'Playstation 5',
          price: 900,
          city: 'Москва',
          placement: 'Страница цен',
          recommendations: 600,
          rate: 400,
          my_rates: true,
          feed: 'азонокосилки Нижний Таггил',
        },
        {
          category: 'Игровая приставка',
          offer: 'Playstation 5',
          price: 800,
          city: 'Москва',
          placement: 'Страница цен',
          recommendations: 600,
          rate: 400,
          my_rates: false,
          feed: 'Еще что то',
        },
        {
          category: 'Игровая приставка',
          offer: 'Playstation 5',
          price: 700,
          city: 'Москва',
          placement: 'Страница цен',
          recommendations: 600,
          rate: 400,
          my_rates: false,
          feed: 'Еще что то',
        },
        {
          category: 'Смартфон',
          offer: 'Xiaomi',
          price: 600,
          city: 'Москва',
          placement: 'Страница цен',
          recommendations: 600,
          rate: 400,
          my_rates: false,
          feed: 'Еще что то',
        },
        {
          category: 'Смартфон',
          offer: 'Samsung',
          price: 500,
          city: 'Москва',
          placement: 'Спец. блок',
          recommendations: 600,
          rate: 400,
          my_rates: false,
          feed: 'Еще что то',
        },
        {
          category: 'Игровая приставка',
          offer: 'Playstation 5',
          price: 500,
          city: 'Москва',
          placement: 'Страница цен',
          recommendations: 600,
          rate: 400,
          my_rates: false,
          feed: 'Еще что то 3',
        },
        {
          category: 'Игровая приставка',
          offer: 'Playstation 5',
          price: 500,
          city: 'Москва',
          placement: 'Страница цен',
          recommendations: 600,
          rate: 400,
          my_rates: false,
          feed: 'Еще что то 5',
        },
        {
          category: 'Игровая приставка',
          offer: 'Playstation 5',
          price: 400,
          city: 'Москва',
          placement: 'Страница цен',
          recommendations: 600,
          rate: 400,
          my_rates: true,
          feed: 'Еще что то 6',
        },
      ],
      columns: [
        {
          dataIndex: 'my_rates',
          key: 'my_rates',
          widget: {
            name: 'checkbox',
          },
          hide: true,
          filterType: 'category',
          filterWidth: '200px',
        },
        {
          dataIndex: 'feed',
          key: 'feed',
          widget: {
            name: 'multiselect',
          },
          hide: true,
        },
        {
          title: 'Категория',
          dataIndex: 'category',
          key: 'category',
          resizable: true,
          widget: {
            name: 'text',
          },
          width: 200,
          filterType: 'category',
          filterWidth: '200px',
          sort: true,
        },
        {
          title: 'Предложение',
          dataIndex: 'offer',
          key: 'offer',
          resizable: true,
          widget: {
            name: 'text',
          },
          width: 200,
          filterType: 'text',
          filterTitle: 'Поиск по названию',
          filterIcon: 'fa-search',
          filterWidth: '220px',
          sort: true,
        },
        {
          title: 'Цена',
          dataIndex: 'price',
          key: 'price',
          resizable: true,
          widget: {
            name: 'text',
          },
          width: 200,
          filterType: 'number',
          filterWidth: '130px',
          sort: true,
        },
        {
          title: 'Город',
          dataIndex: 'city',
          key: 'city',
          resizable: true,
          widget: {
            name: 'text',
          },
          width: 200,
          sort: true,
        },
        {
          title: 'Размещение',
          dataIndex: 'placement',
          key: 'placement',
          resizable: true,
          widget: {
            name: 'text',
          },
          width: 200,
          filterType: 'category',
          sort: true,
        },
        {
          title: 'Рекомендации',
          dataIndex: 'recommendations',
          key: 'recommendations',
          resizable: true,
          widget: {
            name: 'text',
          },
          width: 200,
          sort: true,
        },
        {
          title: 'Ставка',
          dataIndex: 'rate',
          key: 'rate',
          resizable: true,
          widget: {
            name: 'text',
          },
          width: 200,
          sort: true,
        },

        {
          title: 'Действия',
          dataIndex: 'actions',
          widget: {
            name: 'actions',
          },
          width: 20,
          hide: false,
          delete: true,
          edit: true,
          copy: true,
        },
      ],
    },
  ],
}
