export default {
  page: 'representatives',
  title: 'Представители',
  groups: [
    {
      name: 'representatives',
      layoutForm: 'vertical',
      fields: ['title_block', 'body_block', 'blockModal_1'],
    },
  ],
  fields: [
    {
      type: 'button',
      value: 'Добавить представителя',
      name: 'added_button',
      size: 'large',
      buttonType: 'primary',
      disabled: false,
      cssClass: ['mt-6'],
      style: {
        backgroundColor: 'var(--buttonGreen)',
        borderColor: 'var(--buttonGreen)',
      },
      icon: {},
      handler: {
        name: 'editField',
        params: {
          pageName: 'representatives',
          blockName: 'blockModal_1',
          fieldName: 'style',
          value: { display: 'flex' },
        },
      },
    },
    {
      type: 'button',
      value: 'Отмена',
      name: 'close_button',
      size: 'large',
      buttonType: 'primary',
      disabled: false,
      cssClass: ['mt-6'],
      style: {},
      icon: {},
      handler: {
        name: 'editField',
        params: {
          pageName: 'representatives',
          blockName: 'blockModal_1',
          fieldName: 'style',
          value: { display: 'none' },
        },
      },
    },
    {
      layout: 'grid',
      name: 'blockModal_1',
      type: 'div',
      handler: {
        name: 'editField',
        params: {
          pageName: 'representatives',
          blockName: 'blockModal_1',
          fieldName: 'style',
          value: { display: 'none' },
        },
      },
      cssClass: [
        'fixed',
        'bottom-0',
        'left-0',
        'top-0',
        'right-0',
        'z-50',
        'bg-black/40',
        'hidden',
        'justify-center',
        'items-center',
      ],
      style: {},
      fields: ['blockModal_1_content'],
    },
    {
      title: 'Добавление представителя',
      layout: 'grid',
      name: 'blockModal_1_content',
      type: 'div',
      cssClass: [
        'bg-white',
        'p-6',
        'max-w-xl',
        'animate-animation-preview',
        'flex',
        'flex-col',
        'gap-4',
      ],
      style: {},
      fields: [
        'email_input',
        'access_input',
        'schedule_input',
        'login_input',
        'password_input',
        'name_surname_input',
        'phone_number_input',
        'close_button',
      ],
    },
    {
      name: 'title_block',
      type: 'div',
      cssClass: [
        'bg-white',
        'p-6',
        'border-b',
        'border-solid',
        'border-borderColor',
      ],
      style: {},
      fields: ['title'],
    },
    {
      text: 'Представители',
      name: 'title',
      type: 'label',
      cssClass: ['font-medium', 'text-xl'],
      style: {},
    },
    {
      name: 'body_block',
      type: 'div',
      cssClass: ['bg-white', 'p-6'],
      style: {},
      fields: ['select_user_block', 'checkbox_form', 'added_button'],
    },
    {
      description: 'Select User Block',
      name: 'select_user_block',
      type: 'div',
      cssClass: ['pb-6'],
      style: {},
      fields: ['select_user'],
    },
    {
      title: 'Отправлять на sales@auto-geo.ru:',
      name: 'checkbox_form',
      type: 'div',
      cssClass: [
        'mb-10',
        'pb-4',
        'border-b',
        'border-solid',
        'border-borderColor',
      ],
      style: {},
      fields: [
        'check_box_1',
        'check_box_2',
        'check_box_3',
        'check_box_4',
        'check_box_5',
        'check_box_6',
      ],
    },
    {
      title: '',
      label: 'Оповещение о новых заказах',
      required: false,
      name: 'check_box_1',
      value: false,
      type: 'boolean',
      viewType: 'checkbox',
      parentClass: ['pt-4 pb-5'],
      style: {},
    },
    {
      title: '',
      label: 'Еженедельные отчёты о переходах',
      required: false,
      name: 'check_box_2',
      value: false,
      type: 'boolean',
      viewType: 'checkbox',
      parentClass: ['pb-6'],
      style: {},
    },
    {
      title: '',
      label: 'Оповещения за 5 дней и за сутки до расхода баланса',
      required: false,
      name: 'check_box_3',
      value: false,
      type: 'boolean',
      viewType: 'checkbox',
      parentClass: ['pb-6'],
      style: {},
    },
    {
      title: '',
      label: 'Оповещения о расходе баланса',
      required: false,
      name: 'check_box_4',
      value: false,
      type: 'boolean',
      viewType: 'checkbox',
      parentClass: ['pb-6'],
      style: {},
    },
    {
      title: '',
      label: 'Информация о важных изменениях на сайте',
      required: false,
      name: 'check_box_5',
      value: false,
      type: 'boolean',
      viewType: 'checkbox',
      parentClass: ['pb-6'],
      style: {},
    },
    {
      title: '',
      label: 'Оповещения о платежах, счета и закрывающие документы',
      required: false,
      name: 'check_box_6',
      value: false,
      type: 'boolean',
      viewType: 'checkbox',
      parentClass: ['pb-6'],
      style: {},
    },
    {
      title: 'E-mail',
      description: '',
      required: false,
      name: 'email_input',
      format: 'text',
      value: '',
      type: 'input',
    },
    {
      title: 'Доступ',
      description: '',
      subtitle: {
        text: 'Наблюдатель может только просматривать аналитику. Менеджер может ещё редактировать данные. Владелец может ещё добавлять и удалять представителей.',
        cssClass: ['text-xs', 'text-textSecondary'],
        style: {},
      },
      required: false,
      name: 'access_input',
      format: 'text',
      value: 1,
      type: 'select',
      options: [
        {
          id: 1,
          name: 'Владелец',
        },
        {
          id: 2,
          name: 'Наблюдатель',
        },
        {
          id: 3,
          name: 'Менеджер',
        },
      ],
    },
    {
      title: 'График работы',
      description: '',
      subtitle: {
        text: 'Напр: Пн-Пт 09:00 - 18:00; Сб 10:00 - 18:00',
        cssClass: ['text-xs', 'text-textSecondary'],
        style: {},
      },
      required: false,
      name: 'schedule_input',
      format: 'text',
      value: '',
      type: 'input',
    },
    {
      title: 'Логин',
      description: '',
      required: false,
      name: 'login_input',
      format: 'text',
      value: '',
      type: 'input',
    },
    {
      title: 'Пароль',
      description: '',
      subtitle: {
        text: 'Сгенерировать',
        cssClass: ['text-sm', 'text-primary', 'cursor-pointer'],
        style: {},
      },
      required: false,
      name: 'password_input',
      format: 'password',
      value: '',
      type: 'input',
    },
    {
      title: 'Имя Фамилия',
      description: '',
      required: false,
      name: 'name_surname_input',
      format: 'text',
      value: '',
      type: 'input',
    },
    {
      title: 'Телефон',
      description: '',
      required: false,
      name: 'phone_number_input',
      format: 'text',
      value: '',
      mask: '+7 (###) ###-##-##',
      type: 'input',
    },
    {
      title: '',
      description: '',
      required: false,
      name: 'select_user',
      format: 'text',
      value: 1,
      type: 'select',
      options: [
        {
          id: 1,
          name: 'Менеджер (Auto-Geo) - Владелец',
        },
        {
          id: 2,
          name: 'Менеджер (Auto-Geo) - Наблюдатель',
        },
        {
          id: 3,
          name: 'Менеджер (Auto-Geo) - Менеджер',
        },
      ],
    },
  ],
}
