export default {
  page: 'requisites',
  title: 'Реквизиты',
  groups: [
    {
      name: 'requisites',
      layoutForm: 'vertical',
      fields: ['requisites_title', 'requisites_form'],
    },
  ],
  fields: [
    {
      name: 'requisites_title',
      type: 'div',
      cssClass: [
        'bg-white',
        'p-6',
        'border-b',
        'border-solid',
        'border-borderColor',
      ],
      style: {},
      fields: ['title'],
    },
    {
      text: 'Реквизиты',
      name: 'title',
      type: 'label',
      cssClass: ['font-medium', 'text-xl'],
      style: {},
    },
    {
      description: 'Requisites form',
      name: 'requisites_form',
      type: 'div',
      cssClass: ['bg-white', 'p-6', 'flex', 'flex-col', 'gap-4'],
      style: {},
      positionStyle: {},
      fields: [
        'name_organization',
        'ogrn_field',
        'inn_field',
        'kpp_field',
        'juristic_address',
        'checks_copy',
        'save_button',
      ],
    },
    {
      title: '',
      label:
        'Отправлять бумажные копии счетов и закрывающих документов в начале каждого месяца',
      required: false,
      name: 'checks_copy',
      value: false,
      type: 'boolean',
      viewType: 'switch',
      style: {},
      cssClass: ['mb-10'],
    },
    {
      title: 'Название организации',
      description: '',
      subtitle: {
        text: 'Напр. OOO «Интернет-магазин шин»',
        cssClass: ['text-xs', 'text-textSecondary'],
        style: {},
      },
      required: false,
      name: 'name_organization',
      format: 'text',
      value: '',
      type: 'input',
      cssClass: [],
      style: {},
    },
    {
      title: 'ОГРН',
      description: '',
      required: false,
      name: 'ogrn_field',
      format: 'text',
      value: '',
      type: 'input',
    },
    {
      title: 'ИНН',
      description: '',
      required: false,
      name: 'inn_field',
      format: 'text',
      value: '',
      type: 'input',
    },
    {
      title: 'КПП',
      description: '',
      required: false,
      name: 'kpp_field',
      format: 'text',
      value: '',
      type: 'input',
    },
    {
      title: 'Юридический адрес',
      description: '',
      required: false,
      name: 'juristic_address',
      format: 'text',
      value: '',
      type: 'input',
    },
    {
      type: 'button',
      value: 'Сохранить изменения',
      name: 'save_button',
      buttonType: 'primary',
      disabled: false,
      cssClass: ['my-12'],
      icon: {},
      handler: {
        name: 'editField',
        params: {
          pageName: 'requisites',
          blockName: 'save_button',
          fieldName: 'cssClass',
          value: { add: [], remove: [] },
        },
      },
    },
  ],
}
