export default {
  title: 'Список пользователей',
  page: 'users_list_table',
  groups: [
    {
      name: 'users_list_table',
      fields: ['title_block', 'body_block'],
    },
  ],
  fields: [
    {
      name: 'title_block',
      type: 'div',
      cssClass: ['bg-white', 'p-6', 'mb-6', 'flex-col'],
      fields: ['breadcrumbs', 'title'],
    },
    {
      name: 'breadcrumbs',
      type: 'breadcrumbs',
      options: [
        {
          title: 'Главная',
          path: '/',
        },
        {
          title: 'Настройки',
        },
        {
          title: 'Пользователи',
        },
        {
          title: 'Список пользователей',
          path: '/main/users_list_table',
        },
      ],
    },
    {
      text: 'Список пользователей',
      name: 'title',
      type: 'label',
      parentClass: ['mt-4'],
      cssClass: ['font-medium', 'text-xl'],
    },
    {
      name: 'body_block',
      type: 'div',
      cssClass: ['bg-white'],
      fields: ['wrapper_block'],
    },
    {
      name: 'wrapper_block',
      type: 'div',
      cssClass: ['w-full', 'p-6'],
      fields: ['top_block', 'users_table', 'users_add_modal'],
    },
    {
      name: 'top_block',
      type: 'div',
      cssClass: ['text-end'],
      fields: ['users__add_button'],
    },
    {
      type: 'button',
      value: 'Добавить пользователя',
      name: 'users__add_button',
      buttonType: 'primary',
      icon: {
        name: 'fa-solid fa-plus',
      },
      handlers: [
        {
          name: 'editField',
          params: {
            pageName: 'users_list_table',
            blockName: 'users_add_modal',
            fieldName: 'style',
            value: { display: 'flex' },
          },
        },
      ],
    },
    {
      name: 'users_add_modal',
      type: 'div',
      handlers: [
        {
          name: 'editField',
          params: {
            pageName: 'users_list_table',
            blockName: 'users_add_modal',
            fieldName: 'style',
            value: { display: 'none' },
          },
        },
        {
          name: 'resetBlockData',
          params: {
            pageName: 'users_list_table',
            blockName: 'users_add_modal',
          },
        },
      ],
      cssClass: [
        'fixed',
        'bottom-0',
        'left-0',
        'top-0',
        'right-0',
        'z-50',
        'bg-black/40',
        'hidden',
        'justify-center',
        'items-center',
      ],
      style: {},
      fields: ['block_modal_added_content'],
    },
    {
      title: 'Добавление пользователя',
      titleClass: ['font-medium', 'mb-4'],
      name: 'block_modal_added_content',
      type: 'div',
      containerClass: ['bg-white', 'p-6', 'gap-4', 'w-480'],
      fields: [
        'user_login',
        'activity',
        'change_date',
        'user_name',
        'user_surname',
        'user_email',
        'last_date',
        'user_id',
        'buttons_block_footer',
      ],
    },
    {
      title: 'Логин',
      description: '',
      name: 'user_login',
      format: 'text',
      value: '',
      type: 'input',
      excludeSend: true,
      validation: {
        rules: [
          {
            type: 'required',
          },
        ],
      },
    },
    {
      title: 'Активность',
      name: 'activity',
      type: 'radio',
      viewType: 'button',
      excludeSend: true,
      validation: {
        rules: [
          {
            type: 'required',
          },
        ],
      },
      options: [
        {
          value: 'Да',
          label: 'Да',
        },
        {
          value: 'Нет',
          label: 'Нет',
        },
      ],
      value: '',
      parentClass: ['flex', 'flex-col', 'gap-4'],
    },
    {
      title: 'Дата изменения',
      name: 'change_date',
      value: '',
      type: 'datetime',
      displayFormat: 'YYYY-MM-DD',
      format: 'YYYY-MM-DD',
      mode: 'date',
    },
    {
      title: 'Имя',
      name: 'user_name',
      format: 'text',
      value: '',
      type: 'input',
      excludeSend: true,
      validation: {
        rules: [
          {
            type: 'required',
          },
        ],
      },
    },
    {
      title: 'Фамилия',
      name: 'user_surname',
      format: 'text',
      value: '',
      type: 'input',
      excludeSend: true,
      validation: {
        rules: [
          {
            type: 'required',
          },
        ],
      },
    },
    {
      title: 'E-mail',
      name: 'user_email',
      format: 'text',
      value: '',
      type: 'input',
      excludeSend: true,
      validation: {
        rules: [
          {
            type: 'required',
          },
        ],
      },
    },
    {
      title: 'Последняя авторизация',
      name: 'last_date',
      value: '',
      type: 'datetime',
      displayFormat: 'YYYY-MM-DD',
      format: 'YYYY-MM-DD',
      mode: 'date',
    },
    {
      title: 'ID',
      name: 'user_id',
      format: 'text',
      value: '',
      type: 'input',
      excludeSend: true,
      validation: {
        rules: [
          {
            type: 'required',
          },
        ],
      },
    },
    {
      name: 'buttons_block_footer',
      type: 'div',
      cssClass: ['flex', 'justify-end', 'gap-2', 'mt-4'],
      fields: ['template__cancel_button', 'template__add_button'],
    },
    {
      type: 'button',
      value: 'Отменить',
      name: 'template__cancel_button',
      handlers: [
        {
          name: 'editField',
          params: {
            pageName: 'users_list_table',
            blockName: 'users_add_modal',
            fieldName: 'style',
            value: { display: 'none' },
          },
        },
        {
          name: 'resetBlockData',
          params: {
            pageName: 'users_list_table',
            blockName: 'users_add_modal',
          },
        },
      ],
    },
    {
      type: 'button',
      value: 'Добавить',
      name: 'template__add_button',
      buttonType: 'primary',
      handlers: [
        {
          name: 'validateHandler',
          params: {
            pageName: 'users_list_table',
            blockName: 'users_add_modal',
          },
        },
        {
          name: 'addDataToTableField',
          params: {
            pageName: 'users_list_table',
            tableName: 'users_table',
            data: {
              user_login: 'user_login',
              activity: 'activity',
              change_date: 'change_date',
              user_name: 'user_name',
              user_surname: 'user_surname',
              user_email: 'user_email',
              last_date: 'last_date',
              user_id: 'user_id',
            },
          },
        },
        {
          name: 'editField',
          params: {
            pageName: 'users_list_table',
            blockName: 'users_add_modal',
            fieldName: 'style',
            value: { display: 'none' },
          },
        },
        {
          name: 'resetBlockData',
          params: {
            pageName: 'users_list_table',
            blockName: 'users_add_modal',
          },
        },
      ],
    },
    {
      name: 'users_table',
      type: 'table',
      cssClass: ['bg-white'],
      style: {
        borderBottom: '2px solid #f5f5f5',
      },
      config: {
        pagination: true,
        size: 'large',
        align: 'center',
        bordered: true,
        selection: true,
        search: {
          fields: [
            'user_login',
            'user_name',
            'user_surname',
            'user_email',
            'user_id',
          ],
        },
      },
      data: [
        {
          user_login: 'jensenmosley@koffee.com',
          activity: 'Да',
          change_date: 1666803600,
          user_name: 'eu',
          user_surname: 'sint',
          user_email: 'jensenmosley@koffee.com',
          last_date: 1666803600,
          user_id: 947884,
        },
        {
          user_login: 'jensenmosley@koffee.com',
          activity: 'Да',
          change_date: 1666803600,
          user_name: 'deserunt',
          user_surname: 'aute',
          user_email: 'jensenmosley@koffee.com',
          last_date: 1666803600,
          user_id: 327184,
        },
        {
          user_login: 'jensenmosley@koffee.com',
          activity: 'Да',
          change_date: 1666803600,
          user_name: 'id',
          user_surname: 'velit',
          user_email: 'jensenmosley@koffee.com',
          last_date: 1666803600,
          user_id: 247259,
        },
        {
          user_login: 'jensenmosley@koffee.com',
          activity: 'Да',
          change_date: 1666803600,
          user_name: 'culpa',
          user_surname: 'ad',
          user_email: 'jensenmosley@koffee.com',
          last_date: 1666803600,
          user_id: 204413,
        },
        {
          user_login: 'jensenmosley@koffee.com',
          activity: 'Да',
          change_date: 1666803600,
          user_name: 'aliqua',
          user_surname: 'sunt',
          user_email: 'jensenmosley@koffee.com',
          last_date: 1666803600,
          user_id: 413539,
        },
        {
          user_login: 'jensenmosley@koffee.com',
          activity: 'Да',
          change_date: 1666803600,
          user_name: 'esse',
          user_surname: 'duis',
          user_email: 'jensenmosley@koffee.com',
          last_date: 1666803600,
          user_id: 716229,
        },
        {
          user_login: 'jensenmosley@koffee.com',
          activity: 'Да',
          change_date: 1666803600,
          user_name: 'esse',
          user_surname: 'nostrud',
          user_email: 'jensenmosley@koffee.com',
          last_date: 1666803600,
          user_id: 351411,
        },
        {
          user_login: 'jensenmosley@koffee.com',
          activity: 'Да',
          change_date: 1666803600,
          user_name: 'aliqua',
          user_surname: 'aute',
          user_email: 'jensenmosley@koffee.com',
          last_date: 1666803600,
          user_id: 275879,
        },
        {
          user_login: 'jensenmosley@koffee.com',
          activity: 'Да',
          change_date: 1666803600,
          user_name: 'consectetur',
          user_surname: 'commodo',
          user_email: 'jensenmosley@koffee.com',
          last_date: 1666803600,
          user_id: 564368,
        },
        {
          user_login: 'jensenmosley@koffee.com',
          activity: 'Да',
          change_date: 1666803600,
          user_name: 'id',
          user_surname: 'laborum',
          user_email: 'jensenmosley@koffee.com',
          last_date: 1666803600,
          user_id: 130516,
        },
        {
          user_login: 'jensenmosley@koffee.com',
          activity: 'Да',
          change_date: 1666803600,
          user_name: 'labore',
          user_surname: 'consectetur',
          user_email: 'jensenmosley@koffee.com',
          last_date: 1666803600,
          user_id: 885365,
        },
        {
          user_login: 'jensenmosley@koffee.com',
          activity: 'Да',
          change_date: 1666803600,
          user_name: 'sint',
          user_surname: 'velit',
          user_email: 'jensenmosley@koffee.com',
          last_date: 1666803600,
          user_id: 445248,
        },
        {
          user_login: 'jensenmosley@koffee.com',
          activity: 'Да',
          change_date: 1666803600,
          user_name: 'esse',
          user_surname: 'quis',
          user_email: 'jensenmosley@koffee.com',
          last_date: 1666803600,
          user_id: 938221,
        },
        {
          user_login: 'jensenmosley@koffee.com',
          activity: 'Да',
          change_date: 1666803600,
          user_name: 'ea',
          user_surname: 'eu',
          user_email: 'jensenmosley@koffee.com',
          last_date: 1666803600,
          user_id: 739548,
        },
        {
          user_login: 'jensenmosley@koffee.com',
          activity: 'Да',
          change_date: 1666803600,
          user_name: 'eu',
          user_surname: 'aliquip',
          user_email: 'jensenmosley@koffee.com',
          last_date: 1666803600,
          user_id: 502406,
        },
        {
          user_login: 'jensenmosley@koffee.com',
          activity: 'Да',
          change_date: 1666803600,
          user_name: 'et',
          user_surname: 'qui',
          user_email: 'jensenmosley@koffee.com',
          last_date: 1666803600,
          user_id: 988625,
        },
        {
          user_login: 'jensenmosley@koffee.com',
          activity: 'Да',
          change_date: 1666803600,
          user_name: 'duis',
          user_surname: 'ex',
          user_email: 'jensenmosley@koffee.com',
          last_date: 1666803600,
          user_id: 489352,
        },
        {
          user_login: 'jensenmosley@koffee.com',
          activity: 'Да',
          change_date: 1666803600,
          user_name: 'fugiat',
          user_surname: 'voluptate',
          user_email: 'jensenmosley@koffee.com',
          last_date: 1666803600,
          user_id: 305241,
        },
        {
          user_login: 'jensenmosley@koffee.com',
          activity: 'Да',
          change_date: 1666803600,
          user_name: 'mollit',
          user_surname: 'reprehenderit',
          user_email: 'jensenmosley@koffee.com',
          last_date: 1666803600,
          user_id: 943700,
        },
        {
          user_login: 'jensenmosley@koffee.com',
          activity: 'Да',
          change_date: 1666803600,
          user_name: 'elit',
          user_surname: 'duis',
          user_email: 'jensenmosley@koffee.com',
          last_date: 1666803600,
          user_id: 935037,
        },
        {
          user_login: 'jensenmosley@koffee.com',
          activity: 'Да',
          change_date: 1666803600,
          user_name: 'eiusmod',
          user_surname: 'duis',
          user_email: 'jensenmosley@koffee.com',
          last_date: 1666803600,
          user_id: 207370,
        },
        {
          user_login: 'jensenmosley@koffee.com',
          activity: 'Да',
          change_date: 1666803600,
          user_name: 'aliquip',
          user_surname: 'id',
          user_email: 'jensenmosley@koffee.com',
          last_date: 1666803600,
          user_id: 315892,
        },
        {
          user_login: 'jensenmosley@koffee.com',
          activity: 'Да',
          change_date: 1666803600,
          user_name: 'veniam',
          user_surname: 'nisi',
          user_email: 'jensenmosley@koffee.com',
          last_date: 1666803600,
          user_id: 778586,
        },
        {
          user_login: 'jensenmosley@koffee.com',
          activity: 'Да',
          change_date: 1666803600,
          user_name: 'consequat',
          user_surname: 'consequat',
          user_email: 'jensenmosley@koffee.com',
          last_date: 1666803600,
          user_id: 375851,
        },
        {
          user_login: 'jensenmosley@koffee.com',
          activity: 'Да',
          change_date: 1666803600,
          user_name: 'nisi',
          user_surname: 'deserunt',
          user_email: 'jensenmosley@koffee.com',
          last_date: 1666803600,
          user_id: 306864,
        },
        {
          user_login: 'jensenmosley@koffee.com',
          activity: 'Да',
          change_date: 1666803600,
          user_name: 'elit',
          user_surname: 'labore',
          user_email: 'jensenmosley@koffee.com',
          last_date: 1666803600,
          user_id: 615551,
        },
        {
          user_login: 'jensenmosley@koffee.com',
          activity: 'Да',
          change_date: 1666803600,
          user_name: 'sit',
          user_surname: 'cillum',
          user_email: 'jensenmosley@koffee.com',
          last_date: 1666803600,
          user_id: 388714,
        },
        {
          user_login: 'jensenmosley@koffee.com',
          activity: 'Да',
          change_date: 1666803600,
          user_name: 'labore',
          user_surname: 'pariatur',
          user_email: 'jensenmosley@koffee.com',
          last_date: 1666803600,
          user_id: 532768,
        },
        {
          user_login: 'jensenmosley@koffee.com',
          activity: 'Да',
          change_date: 1666803600,
          user_name: 'incididunt',
          user_surname: 'minim',
          user_email: 'jensenmosley@koffee.com',
          last_date: 1666803600,
          user_id: 555908,
        },
        {
          user_login: 'jensenmosley@koffee.com',
          activity: 'Да',
          change_date: 1666803600,
          user_name: 'proident',
          user_surname: 'ullamco',
          user_email: 'jensenmosley@koffee.com',
          last_date: 1666803600,
          user_id: 262137,
        },
        {
          user_login: 'jensenmosley@koffee.com',
          activity: 'Да',
          change_date: 1666803600,
          user_name: 'pariatur',
          user_surname: 'officia',
          user_email: 'jensenmosley@koffee.com',
          last_date: 1666803600,
          user_id: 629870,
        },
        {
          user_login: 'jensenmosley@koffee.com',
          activity: 'Да',
          change_date: 1666803600,
          user_name: 'Lorem',
          user_surname: 'officia',
          user_email: 'jensenmosley@koffee.com',
          last_date: 1666803600,
          user_id: 804198,
        },
        {
          user_login: 'jensenmosley@koffee.com',
          activity: 'Да',
          change_date: 1666803600,
          user_name: 'commodo',
          user_surname: 'nisi',
          user_email: 'jensenmosley@koffee.com',
          last_date: 1666803600,
          user_id: 455666,
        },
        {
          user_login: 'jensenmosley@koffee.com',
          activity: 'Да',
          change_date: 1666803600,
          user_name: 'nulla',
          user_surname: 'proident',
          user_email: 'jensenmosley@koffee.com',
          last_date: 1666803600,
          user_id: 978965,
        },
        {
          user_login: 'jensenmosley@koffee.com',
          activity: 'Да',
          change_date: 1666803600,
          user_name: 'irure',
          user_surname: 'in',
          user_email: 'jensenmosley@koffee.com',
          last_date: 1666803600,
          user_id: 908974,
        },
        {
          user_login: 'jensenmosley@koffee.com',
          activity: 'Да',
          change_date: 1666803600,
          user_name: 'enim',
          user_surname: 'consectetur',
          user_email: 'jensenmosley@koffee.com',
          last_date: 1666803600,
          user_id: 296761,
        },
        {
          user_login: 'jensenmosley@koffee.com',
          activity: 'Да',
          change_date: 1666803600,
          user_name: 'officia',
          user_surname: 'labore',
          user_email: 'jensenmosley@koffee.com',
          last_date: 1666803600,
          user_id: 969167,
        },
        {
          user_login: 'jensenmosley@koffee.com',
          activity: 'Да',
          change_date: 1666803600,
          user_name: 'nisi',
          user_surname: 'aliquip',
          user_email: 'jensenmosley@koffee.com',
          last_date: 1666803600,
          user_id: 523150,
        },
        {
          user_login: 'jensenmosley@koffee.com',
          activity: 'Да',
          change_date: 1666803600,
          user_name: 'occaecat',
          user_surname: 'consectetur',
          user_email: 'jensenmosley@koffee.com',
          last_date: 1666803600,
          user_id: 736813,
        },
        {
          user_login: 'jensenmosley@koffee.com',
          activity: 'Да',
          change_date: 1666803600,
          user_name: 'magna',
          user_surname: 'exercitation',
          user_email: 'jensenmosley@koffee.com',
          last_date: 1666803600,
          user_id: 123470,
        },
        {
          user_login: 'jensenmosley@koffee.com',
          activity: 'Да',
          change_date: 1666803600,
          user_name: 'Lorem',
          user_surname: 'sint',
          user_email: 'jensenmosley@koffee.com',
          last_date: 1666803600,
          user_id: 991135,
        },
        {
          user_login: 'jensenmosley@koffee.com',
          activity: 'Да',
          change_date: 1666803600,
          user_name: 'sunt',
          user_surname: 'quis',
          user_email: 'jensenmosley@koffee.com',
          last_date: 1666803600,
          user_id: 588749,
        },
        {
          user_login: 'jensenmosley@koffee.com',
          activity: 'Да',
          change_date: 1666803600,
          user_name: 'nulla',
          user_surname: 'ea',
          user_email: 'jensenmosley@koffee.com',
          last_date: 1666803600,
          user_id: 829015,
        },
        {
          user_login: 'jensenmosley@koffee.com',
          activity: 'Да',
          change_date: 1666803600,
          user_name: 'consequat',
          user_surname: 'culpa',
          user_email: 'jensenmosley@koffee.com',
          last_date: 1666819856,
          user_id: 893639,
        },
        {
          user_login: 'jensenmosley@koffee.com',
          activity: 'Да',
          change_date: 1666819856,
          user_name: 'cillum',
          user_surname: 'id',
          user_email: 'jensenmosley@koffee.com',
          last_date: 1666819856,
          user_id: 723978,
        },
        {
          user_login: 'jensenmosley@koffee.com',
          activity: 'Да',
          change_date: 1666803600,
          user_name: 'anim',
          user_surname: 'eiusmod',
          user_email: 'jensenmosley@koffee.com',
          last_date: 1666803600,
          user_id: 557183,
        },
        {
          user_login: 'jensenmosley@koffee.com',
          activity: 'Да',
          change_date: 1666803600,
          user_name: 'amet',
          user_surname: 'duis',
          user_email: 'jensenmosley@koffee.com',
          last_date: 1666803600,
          user_id: 630038,
        },
        {
          user_login: 'jensenmosley@koffee.com',
          activity: 'Да',
          change_date: 1666803600,
          user_name: 'enim',
          user_surname: 'sunt',
          user_email: 'jensenmosley@koffee.com',
          last_date: 1666803600,
          user_id: 589971,
        },
        {
          user_login: 'jensenmosley@koffee.com',
          activity: 'Да',
          change_date: 1666803600,
          user_name: 'ullamco',
          user_surname: 'id',
          user_email: 'jensenmosley@koffee.com',
          last_date: 1666803600,
          user_id: 464695,
        },
        {
          user_login: 'jensenmosley@koffee.com',
          activity: 'Да',
          change_date: 1666803600,
          user_name: 'pariatur',
          user_surname: 'nulla',
          user_email: 'jensenmosley@koffee.com',
          last_date: 1666819856,
          user_id: 750443,
        },
        {
          user_login: 'jensenmosley@koffee.com',
          activity: 'Да',
          change_date: 1666819856,
          user_name: 'labore',
          user_surname: 'proident',
          user_email: 'jensenmosley@koffee.com',
          last_date: 1666819856,
          user_id: 437578,
        },
        {
          user_login: 'jensenmosley@koffee.com',
          activity: 'Да',
          change_date: 1666819856,
          user_name: 'minim',
          user_surname: 'duis',
          user_email: 'jensenmosley@koffee.com',
          last_date: 1666803600,
          user_id: 558724,
        },
        {
          user_login: 'jensenmosley@koffee.com',
          activity: 'Да',
          change_date: 1666803600,
          user_name: 'esse',
          user_surname: 'consectetur',
          user_email: 'jensenmosley@koffee.com',
          last_date: 1666814876,
          user_id: 637625,
        },
        {
          user_login: 'jensenmosley@koffee.com',
          activity: 'Да',
          change_date: 1666814876,
          user_name: 'tempor',
          user_surname: 'aute',
          user_email: 'jensenmosley@koffee.com',
          last_date: 1666814876,
          user_id: 896358,
        },
        {
          user_login: 'jensenmosley@koffee.com',
          activity: 'Да',
          change_date: 1666819856,
          user_name: 'nisi',
          user_surname: 'ut',
          user_email: 'jensenmosley@koffee.com',
          last_date: 1666803600,
          user_id: 315227,
        },
        {
          user_login: 'jensenmosley@koffee.com',
          activity: 'Да',
          change_date: 1666803600,
          user_name: 'ex',
          user_surname: 'consectetur',
          user_email: 'jensenmosley@koffee.com',
          last_date: 1666803600,
          user_id: 484305,
        },
        {
          user_login: 'jensenmosley@koffee.com',
          activity: 'Да',
          change_date: 1666814876,
          user_name: 'ad',
          user_surname: 'do',
          user_email: 'jensenmosley@koffee.com',
          last_date: 1666814876,
          user_id: 582455,
        },
        {
          user_login: 'jensenmosley@koffee.com',
          activity: 'Да',
          change_date: 1666803600,
          user_name: 'aliquip',
          user_surname: 'sunt',
          user_email: 'jensenmosley@koffee.com',
          last_date: 1666803600,
          user_id: 625960,
        },
        {
          user_login: 'jensenmosley@koffee.com',
          activity: 'Да',
          change_date: 1666803600,
          user_name: 'velit',
          user_surname: 'aliquip',
          user_email: 'jensenmosley@koffee.com',
          last_date: 1666803600,
          user_id: 960090,
        },
        {
          user_login: 'jensenmosley@koffee.com',
          activity: 'Да',
          change_date: 1666803600,
          user_name: 'deserunt',
          user_surname: 'laborum',
          user_email: 'jensenmosley@koffee.com',
          last_date: 1666814876,
          user_id: 912213,
        },
        {
          user_login: 'jensenmosley@koffee.com',
          activity: 'Да',
          change_date: 1666814876,
          user_name: 'et',
          user_surname: 'enim',
          user_email: 'jensenmosley@koffee.com',
          last_date: 1666803600,
          user_id: 151183,
        },
        {
          user_login: 'jensenmosley@koffee.com',
          activity: 'Да',
          change_date: 1666803600,
          user_name: 'enim',
          user_surname: 'nisi',
          user_email: 'jensenmosley@koffee.com',
          last_date: 1666803600,
          user_id: 165899,
        },
      ],
      columns: [
        {
          title: '',
          dataIndex: 'actions',
          widget: {
            name: 'actions',
          },
          width: 4,
          hide: false,
          delete: true,
          edit: true,
          copy: true,
        },
        {
          title: 'Логин',
          dataIndex: 'user_login',
          key: 'user_login',
          resizable: true,
          widget: {
            name: 'text',
          },
          width: 150,
        },
        {
          title: 'Активность',
          dataIndex: 'activity',
          key: 'activity',
          widget: {
            name: 'text',
          },
          width: 100,
        },
        {
          title: 'Дата изменения',
          dataIndex: 'change_date',
          key: 'change_date',
          widget: {
            name: 'date',
            format: 'DD.MM.YYYY',
          },
          width: 150,
          sort: true,
        },
        {
          title: 'Имя',
          dataIndex: 'user_name',
          key: 'user_name',
          resizable: true,
          widget: {
            name: 'text',
          },
          width: 150,
        },
        {
          title: 'Фамилия',
          dataIndex: 'user_surname',
          key: 'user_surname',
          resizable: true,
          widget: {
            name: 'text',
          },
          width: 150,
        },
        {
          title: 'E-mail',
          dataIndex: 'user_email',
          key: 'user_email',
          resizable: true,
          widget: {
            name: 'text',
          },
          width: 150,
        },
        {
          title: 'Последняя авторизация',
          dataIndex: 'last_date',
          key: 'last_date',
          widget: {
            name: 'date',
            format: 'DD.MM.YYYY',
          },
          width: 150,
          sort: true,
        },
        {
          title: 'ID',
          dataIndex: 'user_id',
          key: 'user_id',
          widget: {
            name: 'text',
          },
          resizable: true,
          width: 150,
        },
      ],
    },
  ],
}
