export default {
  page: 'users_edit',
  title: 'Каталог товаров: Раздел каталога: Редактирование',
  groups: [
    {
      tabName: 'Список пользователей: revolution91@mail.ru: Редактирование',
      name: 'users_edit',
      fields: ['title_block', 'body_block'],
    },
  ],
  fields: [
    {
      name: 'title_block',
      type: 'div',
      cssClass: [
        'bg-white',
        'p-6',
        'mb-6',
        'flex',
        'border-b',
        'border-solid',
        'border-borderColor',
      ],
      fields: ['title'],
    },
    {
      text: 'Список пользователей: revolution91@mail.ru: Редактирование',
      name: 'title',
      type: 'label',
      cssClass: ['font-medium', 'text-xl'],
    },
    {
      name: 'body_block',
      type: 'div',
      cssClass: ['bg-white', 'flex', 'flex-col'],
      fields: [
        'users_list__registration_block',
        'users_list__groups_block',
        'users_list__personal_data_block',
        'user_list__footer',
      ],
    },
    {
      name: 'users_list__registration_block',
      type: 'div',
      fields: ['registration_block__title', 'registration__container_block'],
    },
    {
      name: 'users_list__groups_block',
      type: 'div',
      fields: ['groups_block__title', 'groups_container_block'],
    },
    {
      name: 'users_list__personal_data_block',
      type: 'div',
      fields: ['personal_data_block__title', 'personal_data_container_block'],
    },
    {
      name: 'user_list__footer',
      type: 'div',
      fields: [
        'user_list__buttons_label',
        'user_list__buttons_container_block',
      ],
    },
    {
      name: 'registration_block__title',
      type: 'div',
      cssClass: ['pt-8', 'pl-[430px]'],
      fields: ['title_1'],
    },
    {
      text: 'Регистрационная информация',
      name: 'title_1',
      type: 'label',
      parentClass: [
        'w-max',
        'relative',
        'before:absolute',
        'before:left-[-30px]',
        'before:top-1/2',
        'before:block',
        'before:w-5',
        'before:border-t',
        'before:border-dividerColor',
        'after:absolute',
        'after:right-[-100%]',
        'after:top-1/2',
        'after:block',
        'after:w-[90%]',
        'after:border-t',
        'after:border-dividerColor',
      ],
      cssClass: ['font-medium', 'text-base'],
    },
    {
      name: 'groups_block__title',
      type: 'div',
      cssClass: ['pl-[430px]', 'pt-10', 'pb-5'],
      fields: ['groups_title'],
    },
    {
      name: 'personal_data_block__title',
      type: 'div',
      cssClass: ['pl-[430px]', 'pt-10', 'pb-5'],
      fields: ['personal_data_title'],
    },
    {
      text: 'Группы',
      name: 'groups_title',
      type: 'label',
      parentClass: [
        'w-max',
        'relative',
        'before:absolute',
        'before:left-[-30px]',
        'before:top-1/2',
        'before:block',
        'before:w-5',
        'before:border-t',
        'before:border-dividerColor',
        'after:absolute',
        'after:left-20',
        'after:top-1/2',
        'after:block',
        'after:w-[400px]',
        'after:border-t',
        'after:border-dividerColor',
      ],
      cssClass: ['font-medium', 'text-base', 'w-580'],
    },
    {
      text: 'Личные данные',
      name: 'personal_data_title',
      type: 'label',
      parentClass: [
        'w-max',
        'relative',
        'before:absolute',
        'before:left-[-30px]',
        'before:top-1/2',
        'before:block',
        'before:w-5',
        'before:border-t',
        'before:border-dividerColor',
        'after:absolute',
        'after:left-[9rem]',
        'after:top-1/2',
        'after:block',
        'after:w-[335px]',
        'after:border-t',
        'after:border-dividerColor',
      ],
      cssClass: ['font-medium', 'text-base', 'w-580'],
    },
    {
      name: 'registration__container_block',
      type: 'div',
      cssClass: ['p-6'],
      fields: ['registration__body_block_rigth'],
    },
    {
      name: 'personal_data_container_block',
      type: 'div',
      cssClass: ['p-6'],
      fields: ['personal_data_body_block_rigth'],
    },
    {
      name: 'registration__body_block_rigth',
      type: 'div',
      cssClass: ['flex', 'gap-6', 'ml-40', 'w-700', 'flex-col'],
      fields: [
        'date_registr_text',
        'date_updated_text',
        'date_last_auth_text',
        'active_switch',
        'user_name_input',
        'user_surname_input',
        'user_patronymic_input',
        'user_email_input',
        'user_login_input',
      ],
    },
    {
      name: 'personal_data_body_block_rigth',
      type: 'div',
      cssClass: ['flex', 'gap-6', 'ml-40', 'w-700', 'flex-col'],
      fields: [
        'date_birthday_input',
        'personal_image_input_file',
        'personal_phone_input',
      ],
    },
    {
      name: 'groups_container_block',
      type: 'div',
      cssClass: ['p-6'],
      fields: ['groups__body_block_rigth'],
    },
    {
      name: 'groups__body_block_rigth',
      type: 'div',
      cssClass: ['flex', 'gap-6', 'ml-40', 'w-700', 'flex-col'],
      fields: ['groups_input'],
    },
    {
      title: 'Дата регистрации',
      titlePosition: 'left',
      text: '23.05.2022   17:11:11',
      name: 'date_registr_text',
      type: 'label',
      parentClass: ['w-480', 'font-medium'],
    },
    {
      title: 'Дата обновления',
      titlePosition: 'left',
      text: '23.05.2022   17:15:11',
      name: 'date_updated_text',
      type: 'label',
      parentClass: ['w-480', 'font-medium'],
    },
    {
      title: 'Последняя авторизация',
      titlePosition: 'left',
      text: '23.05.2022   17:20:11',
      name: 'date_last_auth_text',
      type: 'label',
      parentClass: ['w-480', 'font-medium'],
    },
    {
      title: 'Активен',
      titlePosition: 'left',
      name: 'active_switch',
      value: true,
      type: 'boolean',
      viewType: 'switch',
      parentClass: ['w-480'],
    },
    {
      title: 'Имя',
      titlePosition: 'left',
      titleClass: ['mt-2'],
      name: 'user_name_input',
      format: 'text',
      value: '',
      type: 'input',
      parentClass: ['w-480'],
    },
    {
      title: 'Фамилия',
      titlePosition: 'left',
      titleClass: ['mt-2'],
      name: 'user_surname_input',
      format: 'text',
      value: '',
      type: 'input',
      parentClass: ['w-480'],
    },
    {
      title: 'Отчество',
      titlePosition: 'left',
      titleClass: ['mt-2'],
      name: 'user_patronymic_input',
      format: 'text',
      value: '',
      type: 'input',
      parentClass: ['w-480'],
    },
    {
      title: 'E-mail',
      titlePosition: 'left',
      titleClass: ['mt-2'],
      name: 'user_email_input',
      format: 'text',
      value: 'qwerty@mail.ru',
      type: 'input',
      parentClass: ['w-480'],
    },
    {
      title: 'Логин',
      titlePosition: 'left',
      titleClass: ['mt-2'],
      name: 'user_login_input',
      format: 'text',
      value: 'qwerty@mail.ru',
      type: 'input',
      parentClass: ['w-480'],
    },
    {
      title: 'Группы',
      titlePosition: 'left',
      titleClass: ['mt-2'],
      name: 'groups_input',
      format: 'text',
      value: [1],
      type: 'select',
      mode: 'multiple',
      size: 'large',
      cssClass: ['w-480'],
      options: [
        {
          id: 1,
          name: 'Администратор',
        },
        {
          id: 2,
          name: 'Наблюдатель',
        },
        {
          id: 3,
          name: 'Менеджер',
        },
      ],
    },
    {
      title: 'Дата рождения',
      titlePosition: 'left',
      titleClass: ['mt-1'],
      name: 'date_birthday_input',
      value: [],
      type: 'datetime',
      displayFormat: 'YYYY-MM-DD',
      format: 'YYYY-MM-DD',
      mode: 'date',
      cssClass: ['w-480'],
    },
    {
      title: 'Фотография',
      titlePosition: 'left',
      titleClass: ['mt-2'],
      name: 'personal_image_input_file',
      value: '',
      type: 'file',
      maxCount: 1,
      fileType: 'image',
      parentClass: ['h-28', 'w-480'],
    },
    {
      title: 'Телефон',
      titlePosition: 'left',
      titleClass: ['mt-2'],
      name: 'personal_phone_input',
      format: 'text',
      value: '+7 (999) 123-45-67',
      mask: '+7 (###) ###-##-##',
      type: 'input',
      parentClass: ['w-480'],
    },
    {
      name: 'user_list__buttons_container_block',
      type: 'div',
      cssClass: ['flex', 'gap-2', 'ml-[407px]', 'mb-10', 'pb-10'],
      fields: ['user_list__cancel_button', 'user_list__save_button'],
    },
    {
      type: 'button',
      value: 'Сохранить',
      name: 'user_list__save_button',
      size: 'large',
      buttonType: 'primary',
      disabled: false,
      handlers: [
        {
          name: 'pushData',
          params: {
            name: 'users_edit',
          },
        },
      ],
    },
    {
      type: 'button',
      value: 'Отмена',
      name: 'user_list__cancel_button',
      size: 'large',
      buttonType: 'default',
      disabled: false,
    },
  ],
}
