export default {
  view: 'abslayout',
  page: 'edit_page',
  groups: [
    {
      name: 'edit_page',
      layoutForm: 'vertical',
      fields: ['block', 'block2'],
    },
    {
      name: 'Required',
      fields: [
        'feed_product_type_multiple',
        'feed_product_type_tags',
        'slider',
        'feed_product_type',
        'item_sku',
        'brand_name',
        'part_number',
        'manufacturer',
        'product_description',
        'external_product_id',
        'external_product_id_type',
        'model',
        'item_name',
        'item_type',
        'model_name',
        'is_trade_item_orderable_unit',
        'required_product_compliance_certificate',
        'bullet_point1',
        'bullet_point2',
        'bullet_point3',
        'bullet_point4',
        'bullet_point5',
        'bullet_point6',
        'bullet_point7',
        'bullet_point8',
        'bullet_point9',
        'bullet_point10',
        'color_name',
        'department_name',
        'collection_name',
        'lifecycle_supply_type',
        'item_booking_date',
        'item_type_name',
        'number_of_boxes',
        'unit_count_type',
        'unit_count',
        'length_longer_edge',
        'depth_front_to_back',
        'length_longer_edge_unit_of_measure',
        'depth_front_to_back_unit_of_measure',
        'width_shorter_edge',
        'depth_width_side_to_side',
        'width_shorter_edge_unit_of_measure',
        'depth_width_side_to_side_unit_of_measure',
        'depth_height_floor_to_top',
        'depth_height_floor_to_top_unit_of_measure',
        'cpsia_cautionary_statement1',
        'cpsia_cautionary_statement2',
        'cpsia_cautionary_statement3',
        'cpsia_cautionary_statement4',
        'country_of_origin',
        'contains_liquid_contents',
        'is_heat_sensitive',
        'supplier_declared_material_regulation1',
        'supplier_declared_material_regulation2',
        'supplier_declared_material_regulation3',
        'condition_type',
        'currency',
        'number_of_items',
        'is_expiration_dated_product',
        'map_price',
        'main_image_url',
        'age_range_description',
        'target_gender',
        'quantity',
        'standard_price',
      ],
    },
    {
      name: 'Variation',
      fields: [
        'relationship_type',
        'package_level',
        'variation_theme',
        'parent_sku',
        'package_contains_quantity',
        'package_contains_identifier',
        'parent_child',
      ],
    },
    {
      name: 'Basic',
      fields: [
        'update_delete',
        'gtin_exemption_reason',
        'closure_type',
        'care_instructions1',
        'care_instructions2',
        'care_instructions3',
        'model_year',
        'outer_material_type',
      ],
    },
    {
      name: 'Discovery',
      fields: [
        'compatible_devices1',
        'compatible_devices2',
        'compatible_devices3',
        'compatible_devices4',
        'compatible_devices5',
        'golf_club_loft_unit_of_measure',
        'seating_group',
        'option_type',
        'target_audience_base',
        'catalog_number',
        'breed_recommendation',
        'style_keywords1',
        'style_keywords2',
        'style_keywords3',
        'style_keywords4',
        'style_keywords5',
        'specific_uses_keywords1',
        'specific_uses_keywords2',
        'specific_uses_keywords3',
        'specific_uses_keywords4',
        'specific_uses_keywords5',
        'thesaurus_attribute_keywords1',
        'thesaurus_attribute_keywords2',
        'thesaurus_attribute_keywords3',
        'thesaurus_attribute_keywords4',
        'thesaurus_attribute_keywords5',
        'target_audience_keywords1',
        'target_audience_keywords2',
        'target_audience_keywords3',
        'target_audience_keywords4',
        'target_audience_keywords5',
        'thesaurus_subject_keywords1',
        'thesaurus_subject_keywords2',
        'thesaurus_subject_keywords3',
        'thesaurus_subject_keywords4',
        'thesaurus_subject_keywords5',
        'platinum_keywords1',
        'platinum_keywords2',
        'platinum_keywords3',
        'platinum_keywords4',
        'platinum_keywords5',
        'country_as_labeled',
        'skin_type1',
        'skin_type2',
        'skin_type3',
        'skin_type4',
        'skin_type5',
        'skin_tone1',
        'skin_tone2',
        'skin_tone3',
        'skin_tone4',
        'skin_tone5',
        'toe_style',
        'hair_type1',
        'hair_type2',
        'hair_type3',
        'hair_type4',
        'hair_type5',
        'included_features',
        'indications',
        'shade_material_type',
        'directions',
        'specialty1',
        'specialty2',
        'specialty3',
        'specialty4',
        'specialty5',
        'number_of_light_sources',
        'number_of_blades',
        'number_of_sets',
        'horsepower',
        'horsepower_unit_of_measure',
        'sport_type',
        'occasion',
        'voltage',
        'maximum_compatible_light_source_wattage',
        'voltage_unit_of_measure',
        'maximum_current',
        'maximum_current_unit_of_measure',
        'flavor_name',
        'temperature_range_base',
        'brightness_unit_of_measure',
        'temperature_range_unit_of_measure',
        'color_temperature',
        'maximum_flow_rate',
        'maximum_flow_rate_unit_of_measure',
        'includes_rechargable_battery',
        'lithium_battery_voltage',
        'water_consumption',
        'water_consumption_unit_of_measure',
        'air_flow_capacity',
        'air_flow_capacity_unit_of_measure',
        'number_of_pieces',
        'scent_name',
        'maximum_operating_pressure',
        'maximum_operating_pressure_unit_of_measure',
        'capacity_name',
        'included_components1',
        'included_components2',
        'included_components3',
        'included_components4',
        'included_components5',
        'color_temperature_unit_of_measure',
        'handle_location',
        'number_of_handles',
        'specification_met1',
        'specification_met2',
        'specification_met3',
        'screw_head_style',
        'light_source_type',
        'brightness',
        'wattage',
        'hole_count',
        'spout_reach',
        'spout_reach_unit_of_measure',
        'special_features1',
        'special_features2',
        'special_features3',
        'special_features4',
        'special_features5',
        'toilet_rough_in_measurement',
        'toilet_rough_in_measurement_unit_of_measure',
        'folded_size',
        'blade_edge_type',
        'is_stain_resistant',
        'speed',
        'fur_description',
        'speed_rating',
        'pattern_type',
        'maximum_power',
        'water_resistance_level',
        'maximum_power_unit_of_measure',
        'lifestyle',
        'item_torque',
        'item_torque_unit_of_measure',
        'point_type',
        'fastening_type',
        'compatible_fastener_description',
        'measurement_accuracy',
        'viewable_area',
        'ultraviolet_light_protection',
        'grit_number',
        'grit_type',
        'minimum_efficiency_reporting_value',
        'insulation_resistance',
        'display_type',
        'plug_type',
        'battery_average_life',
        'battery_average_life_unit_of_measure',
        'battery_description',
        'golf_club_loft',
        'grip_type',
        'seasons1',
        'seasons2',
        'seasons3',
        'seasons4',
        'seating_capacity',
        'lens_color',
        'lens_material_type',
        'insulation_material_type',
        'hand_orientation',
        'shaft_material',
        'generic_keywords',
        'size_name',
        'color_map',
        'frame_material_type',
        'material_type1',
        'material_type2',
        'material_type3',
        'material_type4',
        'material_type5',
        'handle_material',
        'pattern_name',
        'wattage_unit_of_measure',
        'athlete',
        'team_name',
        'length_range',
        'is_assembly_required',
        'fill_material_type',
        'number_of_shelves',
        'number_of_compartments',
        'style_name',
        'target_species1',
        'target_species2',
        'target_species3',
        'target_species4',
        'target_species5',
        'oem_equivalent_part_number',
        'controller_type',
        'installation_type',
        'cover_material_type',
        'recommended_uses_for_product',
        'assembly_instructions',
        'compatible_counter_depth',
        'is_dishwasher_safe',
        'material_type_free1',
        'material_type_free2',
        'material_type_free3',
        'material_type_free4',
        'material_type_free5',
        'runtime_unit_of_measure',
        'power_source_type',
        'mounting_type',
        'noise_level_unit_of_measure',
        'noise_level',
        'compatible_counter_depth_unit_of_measure',
        'runtime',
        'melting_temperature',
        'melting_temperature_unit_of_measure',
        'seat_depth',
        'number_of_drawers',
        'seat_depth_unit',
        'lithium_battery_voltage_unit_of_measure',
        'shaft_style_type',
        'cylinder_axis',
        'cylinder_correction',
        'base_curve_radius_unit_of_measure',
        'lens_addition_power',
        'optical_power',
        'base_curve_radius',
        'lens_addition_power_unit_of_measure',
        'optical_power_unit_of_measure',
        'operating_life',
        'operating_life_unit_of_measure',
        'maximum_compatible_light_source_wattage_unit_of_measure',
        'battery_charge_time_unit_of_measure',
        'minimum_circumference',
        'product_benefit',
        'minimum_circumference_unit_of_measure',
        'battery_charge_time',
        'floor_area',
        'floor_area_unit_of_measure',
        'is_autographed',
        'weave_type',
        'league_name',
        'human_interface_input1',
        'human_interface_input2',
        'human_interface_input3',
        'human_interface_input4',
        'human_interface_input5',
        'occasion_type1',
        'occasion_type2',
        'occasion_type3',
        'occasion_type4',
        'occasion_type5',
        'number_of_teeth',
        'shank_type',
        'chamber_depth_unit_of_measure',
        'chamber_depth',
        'number_of_doors',
        'maximum_gap_fill',
        'maximum_gap_fill_unit_of_measure',
      ],
    },
    {
      name: 'Product Enrichment',
      fields: [
        'shipping_options',
        'coverage',
        'finish_type1',
        'finish_type2',
        'finish_type3',
        'finish_type4',
        'finish_type5',
        'thread_count',
        'outside_diameter_unit_of_measure',
        'inside_diameter_string',
        'inside_diameter_unit_of_measure',
        'thread_pitch_string',
        'switch_type',
        'golf_club_flex',
        'mfg_minimum',
        'material_composition',
        'tension_level',
        'mfg_maximum',
      ],
    },
    {
      name: 'Dimensions',
      fields: [
        'head_size_name',
        'volume_capacity_name_unit_of_measure',
        'website_shipping_weight_unit_of_measure',
        'website_shipping_weight',
        'item_form',
        'cable_length_unit_of_measure',
        'item_display_volume',
        'item_display_volume_unit_of_measure',
        'maximum_pressure',
        'shoe_width',
        'fabric_weight',
        'maximum_weight_capacity',
        'item_shape',
        'maximum_weight_capacity_unit_of_measure',
        'each_unit_count',
        'extension_length',
        'extension_length_unit_of_measure',
        'total_eaches',
        'hose_length',
        'light_source_length',
        'item_display_length_unit_of_measure',
        'hose_length_unit_of_measure',
        'light_source_length_unit_of_measure',
        'strand_diameter',
        'strand_diameter_unit_of_measure',
        'item_display_width_unit_of_measure',
        'outside_diameter',
        'item_display_height_unit_of_measure',
        'spout_height',
        'spout_height_unit_of_measure',
        'tubing_outside_diameter',
        'tubing_outside_diameter_unit_of_measure',
        'blade_length',
        'blade_length_unit_of_measure',
        'item_display_length',
        'item_display_width',
        'weighted_annual_energy_consumption',
        'measurement_system',
        'weighted_annual_energy_consumption_unit_of_measure',
        'item_display_height',
        'light_source_diameter',
        'light_source_diameter_unit_of_measure',
        'item_display_weight',
        'item_display_weight_unit_of_measure',
        'item_display_diameter',
        'item_display_diameter_unit_of_measure',
        'item_diameter_derived',
        'item_diameter_unit_of_measure',
        'grip_size',
        'item_thickness_derived',
        'item_thickness_unit_of_measure',
        'volume_capacity_name',
        'shaft_length',
        'shaft_length_unit_of_measure',
        'display_maximum_weight_recommendation',
        'display_maximum_weight_recommendation_unit_of_measure',
        'item_width_unit_of_measure',
        'item_height_unit_of_measure',
        'item_width',
        'item_height',
        'size_map',
        'item_length_unit_of_measure',
        'item_length',
        'fabric_weight_unit_of_measure',
        'width_range',
        'maximum_weight_recommendation_unit_of_measure',
        'maximum_weight_recommendation',
        'item_firmness_description',
        'liquid_volume',
        'liquid_volume_unit_of_measure',
        'capacity_unit_of_measure',
        'capacity',
        'maximum_size',
        'maximum_size_unit_of_measure',
        'load_capacity',
        'load_capacity_unit_of_measure',
        'item_display_depth',
        'item_display_depth_unit_of_measure',
        'item_dimensions_unit_of_measure',
        'display_dimensions_unit_of_measure',
        'maximum_pressure_unit_of_measure',
        'item_diameter_string',
        'maximum_circumference',
        'maximum_circumference_unit_of_measure',
        'chamber_height_unit_of_measure',
        'chamber_width_unit_of_measure',
        'chamber_width',
        'chamber_height',
        'weight_recommendation_unit_of_measure',
        'item_depth',
      ],
    },
    {
      name: 'Fulfillment',
      fields: [
        'package_height_unit_of_measure',
        'package_length',
        'package_width',
        'package_weight_unit_of_measure',
        'package_height',
        'package_width_unit_of_measure',
        'fulfillment_center_id',
        'package_length_unit_of_measure',
        'package_weight',
        'is_fragile',
        'package_dimensions_unit_of_measure',
      ],
    },
    {
      name: 'Compliance',
      fields: [
        'energy_efficiency_image_url',
        'warranty_type',
        'warranty_description',
        'seller_warranty_description',
        'allergen_information1',
        'allergen_information2',
        'allergen_information3',
        'allergen_information4',
        'allergen_information5',
        'storage_instructions',
        'fabric_type1',
        'fabric_type2',
        'fabric_type3',
        'fabric_type4',
        'fabric_type5',
        'import_designation',
        'specific_uses_for_product1',
        'specific_uses_for_product2',
        'specific_uses_for_product3',
        'specific_uses_for_product4',
        'specific_uses_for_product5',
        'ingredients',
        'is_adult_product',
        'legal_disclaimer_description',
        'cpsia_cautionary_description',
        'safety_warning',
        'country_string',
        'usda_hardiness_zone1',
        'usda_hardiness_zone2',
        'batteries_required',
        'are_batteries_included',
        'battery_cell_composition',
        'battery_type1',
        'battery_type2',
        'battery_type3',
        'number_of_batteries1',
        'number_of_batteries2',
        'number_of_batteries3',
        'battery_weight',
        'battery_weight_unit_of_measure',
        'number_of_lithium_metal_cells',
        'number_of_lithium_ion_cells',
        'lithium_battery_packaging',
        'lithium_battery_energy_content',
        'lithium_battery_energy_content_unit_of_measure',
        'lithium_battery_weight',
        'lithium_battery_weight_unit_of_measure',
        'supplier_declared_dg_hz_regulation1',
        'supplier_declared_dg_hz_regulation2',
        'supplier_declared_dg_hz_regulation3',
        'supplier_declared_dg_hz_regulation4',
        'supplier_declared_dg_hz_regulation5',
        'hazmat_united_nations_regulatory_id',
        'safety_data_sheet_url',
        'item_weight',
        'item_weight_unit_of_measure',
        'item_volume',
        'item_volume_unit_of_measure',
        'legal_compliance_certification_expiration_date',
        'legal_compliance_certification_regulatory_organization_name',
        'legal_compliance_certification_status',
        'flash_point',
        'legal_compliance_certification_metadata',
        'legal_compliance_certification_value',
        'legal_compliance_certification_date_of_issue',
        'liquid_contents_description',
        'external_testing_certification',
        'lighting_facts_image_url',
        'ghs_classification_class1',
        'ghs_classification_class2',
        'ghs_classification_class3',
        'california_proposition_65_compliance_type',
        'california_proposition_65_chemical_names1',
        'california_proposition_65_chemical_names2',
        'california_proposition_65_chemical_names3',
        'california_proposition_65_chemical_names4',
        'california_proposition_65_chemical_names5',
        'pesticide_marking_type1',
        'pesticide_marking_type2',
        'pesticide_marking_type3',
        'pesticide_marking_registration_status1',
        'pesticide_marking_registration_status2',
        'pesticide_marking_registration_status3',
        'pesticide_marking_certification_number1',
        'pesticide_marking_certification_number2',
        'pesticide_marking_certification_number3',
        'fcc_radio_frequency_emission_compliance_registration_status',
        'fcc_radio_frequency_emission_compliance_point_of_contact_email',
        'fcc_radio_frequency_emission_compliance_point_of_contact_phone_number',
        'fcc_radio_frequency_emission_compliance_point_of_contact_name',
        'fcc_radio_frequency_emission_compliance_identification_number',
        'fcc_radio_frequency_emission_compliance_point_of_contact_address',
      ],
    },
    {
      name: 'Offer',
      fields: [
        'is_discontinued_by_manufacturer',
        'product_site_launch_date',
        'max_aggregate_ship_quantity',
        'delivery_schedule_group_id',
        'item_package_quantity',
        'offering_can_be_giftwrapped',
        'merchant_release_date',
        'offering_end_date',
        'list_price',
        'max_order_quantity',
        'merchant_shipping_group_name',
        'offering_start_date',
        'restock_date',
        'product_tax_code',
        'fulfillment_latency',
        'offering_can_be_gift_messaged',
        'product_expiration_type',
        'fc_shelf_life',
        'condition_note',
        'sale_price',
        'sale_from_date',
        'sale_end_date',
      ],
    },
    {
      name: 'B2B',
      fields: [
        'business_price',
        'quantity_price_type',
        'quantity_lower_bound1',
        'quantity_price1',
        'quantity_lower_bound2',
        'quantity_price2',
        'quantity_lower_bound3',
        'quantity_price3',
        'quantity_lower_bound4',
        'quantity_price4',
        'quantity_lower_bound5',
        'quantity_price5',
        'progressive_discount_type',
        'progressive_discount_lower_bound1',
        'progressive_discount_value1',
        'progressive_discount_lower_bound2',
        'progressive_discount_value2',
        'progressive_discount_lower_bound3',
        'progressive_discount_value3',
        'national_stock_number',
        'unspsc_code',
        'pricing_action',
      ],
    },
  ],
  fields: [
    {
      description: 'block',
      layout: 'grid',
      positionStyle: {
        display: 'grid',
        gridTemplateColumns: 'repeat(2, 1fr)',
        gridTemplateRows: 'repeat(2, 1fr)',
        gridColumnGap: '10px',
        gridRowGap: '10px',
      },
      name: 'block',
      type: 'div',
      style: {
        border: 'solid 2px black',
        borderRadius: '20px',
        padding: '5px',
      },
      fields: ['item_sku', 'block2', 'block4', 'block5'],
    },
    {
      layout: 'absolute',
      required: false,
      name: 'block2',
      type: 'div',
      style: {
        border: 'solid 2px black',
        borderRadius: '5px',
        height: '100px',
      },
      fields: ['item_sku2', 'feed_product_type_multiple'],
    },
    {
      layout: 'absolute',
      required: false,
      name: 'block3',
      type: 'div',
      style: {
        border: 'solid 2px black',
        borderRadius: '5px',
        height: '100px',
      },
      fields: [],
    },
    {
      layout: 'grid',
      name: 'block4',
      type: 'div',
      positionStyle: {
        gridTemplateColumns: 'repeat(2, 1fr)',
        gridTemplateRows: 'repeat(1, 1fr)',
        gridColumnGap: '10px',
        gridRowGap: '10px',
        display: 'grid',
      },
      style: {
        border: 'solid 2px black',
        borderRadius: '5px',
        padding: '5px',
      },
      fields: ['block3', 'block3'],
    },
    {
      required: false,
      name: 'block5',
      type: 'div',
      style: {
        border: 'solid 2px green',
        borderRadius: '5px',
        height: '100px',
      },
      label: 'div',
      fields: ['model', 'model'],
    },
    {
      title: 'Product Type',
      description: 'Input an approprate product type.',
      required: true,
      name: 'feed_product_type_multiple',
      value: 1,
      type: 'select',
      mode: 'multiple',
      options: [
        {
          id: 1,
          name: 'umbrella',
        },
        {
          id: 2,
          name: 'pillow',
        },
        {
          id: 3,
          name: 'leash',
        },
      ],
    },
    {
      title: 'Product Type',
      description: 'Input an approprate product type.',
      required: true,
      name: 'feed_product_type_tags',
      value: 1,
      type: 'select',
      mode: 'tags',
      options: [
        {
          id: 1,
          name: 'umbrella',
        },
        {
          id: 2,
          name: 'pillow',
        },
        {
          id: 3,
          name: 'leash',
        },
      ],
    },
    {
      title: 'Slider',
      description: 'Unique Identifier. 1',
      required: true,
      name: 'slider',
      value: 100,
      type: 'slider',
      viewType: 'slider',
      label: 'slider', // for checkbox
    },
    {
      title: 'Product Type',
      description: 'Input an approprate product type.',
      required: true,
      name: 'feed_product_type',
      value: 1,
      type: 'select',
      options: [
        {
          id: 1,
          name: 'umbrella',
        },
        {
          id: 2,
          name: 'pillow',
        },
        {
          id: 3,
          name: 'leash',
        },
        {
          id: 4,
          name: 'door',
        },
        {
          id: 5,
          name: 'footrest',
        },
        {
          id: 6,
          name: 'foodblender',
        },
        {
          id: 7,
          name: 'beautymisc',
        },
        {
          id: 8,
          name: 'aromadiffuser',
        },
        {
          id: 9,
          name: 'hardware',
        },
        {
          id: 10,
          name: 'essentialoil',
        },
        {
          id: 11,
          name: 'lightfixture',
        },
        {
          id: 12,
          name: 'blanket',
        },
        {
          id: 13,
          name: 'pitcher',
        },
        {
          id: 14,
          name: 'massager',
        },
        {
          id: 15,
          name: 'mousepad',
        },
        {
          id: 16,
          name: 'humidifier',
        },
        {
          id: 17,
          name: 'pillowcase',
        },
        {
          id: 18,
          name: 'shoeaccessory',
        },
        {
          id: 19,
          name: 'coffeemaker',
        },
        {
          id: 20,
          name: 'lamp',
        },
        {
          id: 21,
          name: 'pumpdispenser',
        },
        {
          id: 22,
          name: 'storagebox',
        },
        {
          id: 23,
          name: 'icechest',
        },
        {
          id: 24,
          name: 'bodypositioner',
        },
        {
          id: 25,
          name: 'bedandbath',
        },
        {
          id: 26,
          name: 'draftstopper',
        },
        {
          id: 27,
          name: 'mattresscover',
        },
      ],
      style: {
        width: '250px',
        backgroundColor: 'red',
        border: '4px solid black',
      },
      cssClass: ['some-class', 'awesome'],
      css: '.body{background-color: red}',
    },
    {
      title: 'Seller SKU',
      description: 'Unique Identifier.',
      required: true,
      name: 'item_sku2',
      value: false,
      type: 'boolean',
      viewType: 'checkbox',
      label: 'aaa', // for checkbox
      style: {
        edit_page: {
          width: '250px',
          backgroundColor: 'red',
          border: '4px solid black',
        },
      },
      positionStyle: {
        position: 'absolute',
        top: '20px',
        left: '20px',
      },
      cssClass: ['some-class', 'awesome'],
    },
    {
      title: 'Seller SKU',
      description: 'Unique Identifier.',
      required: true,
      name: 'item_sku',
      value: false,
      type: 'boolean',
      viewType: 'checkbox',
      label: 'aaa', // for checkbox
      style: {
        edit_page: {
          width: '250px',
          backgroundColor: 'red',
          border: '4px solid black',
        },
        Required: {
          width: '250px',
          backgroundColor: 'green',
          border: '4px solid black',
        },
      },
      cssClass: ['some-class', 'awesome'],
    },
    {
      title: 'Seller SKU',
      required: true,
      name: 'item_sku',
      value: 6,
      type: 'radio',
      options: [
        { label: 10, value: 10 },
        { label: 15, value: 15 },
        { label: 6, value: 6 },
      ],
    },
    // {
    // 	title: "Seller Date",
    // 	required: true,
    // 	description: "Select date",
    // 	name: "item_sku",
    // 	value: "",
    // 	type: "datetime",
    // 	time: true,
    // 	displayFormat: "YYYY-MM-DD HH:mm:ss",
    // 	format: "YYYY-MM-DD HH:mm:ss",
    // 	mode: "date",
    // },
    {
      title: 'Brand Image',
      description: 'Max. 50 characters',
      required: true,
      name: 'brand_name',
      value: '',
      type: 'file',
      maxCount: 3,
      fileType: 'image', // image || file
      style: {
        width: '250px',
        backgroundColor: 'red',
        border: '4px solid black',
      },
      cssClass: ['some-class', 'awesome'],
    },
    {
      title: 'Manufacturer Part Number',
      description:
        'An alphanumeric string; 1 character minimum in length and 40 characters maximum in length.',
      required: true,
      name: 'part_number',
      value: '',
      type: 'textarea',
      minRows: 2,
      maxRows: 5,
      style: {
        width: '250px',
        backgroundColor: 'red',
        border: '4px solid black',
      },
      cssClass: ['some-class', 'awesome'],
    },
    {
      title: 'Manufacturer',
      description: 'An alphanumeric string; 50 characters maximum.',
      required: true,
      name: 'manufacturer',
      format: 'text',
      value: 'Repel Umbrella',
      type: 'input',
      style: {
        width: '250px',
        backgroundColor: 'red',
        border: '4px solid black',
      },
      cssClass: ['some-class', 'awesome'],
    },
  ],
}
